"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .instructrequest import InstructRequest, InstructRequestTypedDict
from typing import List, Union
from typing_extensions import TypeAliasType


ChatClassificationRequestInputsTypedDict = TypeAliasType(
    "ChatClassificationRequestInputsTypedDict",
    Union[InstructRequestTypedDict, List[InstructRequestTypedDict]],
)
r"""Chat to classify"""


ChatClassificationRequestInputs = TypeAliasType(
    "ChatClassificationRequestInputs", Union[InstructRequest, List[InstructRequest]]
)
r"""Chat to classify"""
