"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 4926d4da3479

from __future__ import annotations
from .conversationevents import ConversationEvents, ConversationEventsTypedDict
from .conversationresponse import ConversationResponse, ConversationResponseTypedDict
from mistralai.client.utils import eventstreaming
from typing import Union
from typing_extensions import TypeAliasType


AgentsAPIV1ConversationsStartResponseTypedDict = TypeAliasType(
    "AgentsAPIV1ConversationsStartResponseTypedDict",
    Union[
        ConversationResponseTypedDict,
        Union[
            eventstreaming.EventStream[ConversationEventsTypedDict],
            eventstreaming.EventStreamAsync[ConversationEventsTypedDict],
        ],
    ],
)


AgentsAPIV1ConversationsStartResponse = TypeAliasType(
    "AgentsAPIV1ConversationsStartResponse",
    Union[
        ConversationResponse,
        Union[
            eventstreaming.EventStream[ConversationEvents],
            eventstreaming.EventStreamAsync[ConversationEvents],
        ],
    ],
)
