"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mistralai.client.types import BaseModel
from mistralai.client.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AgentHandoffStartedEventTypedDict(TypedDict):
    id: str
    previous_agent_id: str
    previous_agent_name: str
    type: Literal["agent.handoff.started"]
    created_at: NotRequired[datetime]
    output_index: NotRequired[int]


class AgentHandoffStartedEvent(BaseModel):
    id: str

    previous_agent_id: str

    previous_agent_name: str

    TYPE: Annotated[
        Annotated[
            Literal["agent.handoff.started"],
            AfterValidator(validate_const("agent.handoff.started")),
        ],
        pydantic.Field(alias="type"),
    ] = "agent.handoff.started"

    created_at: Optional[datetime] = None

    output_index: Optional[int] = 0
