"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 376cd8ead269

from __future__ import annotations
from datetime import datetime
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Any, Dict, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


MetricValueTypedDict = TypeAliasType("MetricValueTypedDict", Union[float, int])


MetricValue = TypeAliasType("MetricValue", Union[float, int])


class AggregationRowTypedDict(TypedDict):
    metric_name: str
    time_bucket: NotRequired[Nullable[datetime]]
    dimensions: NotRequired[Dict[str, Any]]
    metric_value: NotRequired[Nullable[MetricValueTypedDict]]


class AggregationRow(BaseModel):
    metric_name: str

    time_bucket: OptionalNullable[datetime] = UNSET

    dimensions: Optional[Dict[str, Any]] = None

    metric_value: OptionalNullable[MetricValue] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["time_bucket", "dimensions", "metric_value"])
        nullable_fields = set(["time_bucket", "metric_value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
