"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 62e1e2ab1ce8

from __future__ import annotations
from mistralai.client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AliasListTypedDict(TypedDict):
    r"""Presence wrapper for a set of alias labels on update RPCs. As a message field it carries presence, so callers can distinguish \"leave aliases unchanged\" (field omitted) from \"clear all aliases\" (field set, empty ``values``)."""

    values: NotRequired[List[str]]


class AliasList(BaseModel):
    r"""Presence wrapper for a set of alias labels on update RPCs. As a message field it carries presence, so callers can distinguish \"leave aliases unchanged\" (field omitted) from \"clear all aliases\" (field set, empty ``values``)."""

    values: Optional[List[str]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["values"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
