"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 5d4941eccb81

from __future__ import annotations
from .paginatedresult_campaignpreview_ import (
    PaginatedResultCampaignPreview,
    PaginatedResultCampaignPreviewTypedDict,
)
from mistralai.client.types import BaseModel
from typing_extensions import TypedDict


class CampaignPreviewsTypedDict(TypedDict):
    campaigns: PaginatedResultCampaignPreviewTypedDict


class CampaignPreviews(BaseModel):
    campaigns: PaginatedResultCampaignPreview
