"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionresponsetokenlogprobstopk import (
    ChatCompletionResponseTokenLogprobsTopK,
    ChatCompletionResponseTokenLogprobsTopKTypedDict,
)
from mistralai.client.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ChatCompletionResponseChoiceLogprobsTypedDict(TypedDict):
    content: List[ChatCompletionResponseTokenLogprobsTopKTypedDict]


class ChatCompletionResponseChoiceLogprobs(BaseModel):
    content: List[ChatCompletionResponseTokenLogprobsTopK]
