"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 0e1e1de3c834

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Dict, Literal
from typing_extensions import Annotated, TypedDict


class ClassificationMetricsTypedDict(TypedDict):
    nb_records: int
    nb_undefined: int
    counts: Dict[str, int]
    type: Literal["CLASSIFICATION"]


class ClassificationMetrics(BaseModel):
    nb_records: int

    nb_undefined: int

    counts: Dict[str, int]

    type: Annotated[
        Annotated[
            Literal["CLASSIFICATION"], AfterValidator(validate_const("CLASSIFICATION"))
        ],
        pydantic.Field(alias="type"),
    ] = "CLASSIFICATION"


try:
    ClassificationMetrics.model_rebuild()
except NameError:
    pass
