"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 73ca3a446dcc

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ConnectorGetV1RequestTypedDict(TypedDict):
    connector_id_or_name: str
    fetch_user_data: NotRequired[bool]
    r"""Fetch the user-level data associated with the connector (e.g. connection credentials)."""
    fetch_customer_data: NotRequired[bool]
    r"""Fetch the customer data associated with the connector (e.g. customer secrets / config)."""


class ConnectorGetV1Request(BaseModel):
    connector_id_or_name: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    fetch_user_data: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False
    r"""Fetch the user-level data associated with the connector (e.g. connection credentials)."""

    fetch_customer_data: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False
    r"""Fetch the customer data associated with the connector (e.g. customer secrets / config)."""
