"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: c4f7a932bd2e

from __future__ import annotations
from .audiocontent import AudioContent, AudioContentTypedDict
from .connectortoolcallmetadata import (
    ConnectorToolCallMetadata,
    ConnectorToolCallMetadataTypedDict,
)
from .embeddedresource import EmbeddedResource, EmbeddedResourceTypedDict
from .imagecontent import ImageContent, ImageContentTypedDict
from .resourcelink import ResourceLink, ResourceLinkTypedDict
from .textcontent import TextContent, TextContentTypedDict
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import ConfigDict, Field, model_serializer
from typing import Any, Dict, List, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


ConnectorToolCallResponseContentTypedDict = TypeAliasType(
    "ConnectorToolCallResponseContentTypedDict",
    Union[
        TextContentTypedDict,
        EmbeddedResourceTypedDict,
        ImageContentTypedDict,
        AudioContentTypedDict,
        ResourceLinkTypedDict,
    ],
)


ConnectorToolCallResponseContent = Annotated[
    Union[TextContent, ImageContent, AudioContent, ResourceLink, EmbeddedResource],
    Field(discriminator="type"),
]


class ConnectorToolCallResponseTypedDict(TypedDict):
    r"""Response from calling an MCP tool.

    We override mcp_types.CallToolResult because:
    - Models only support `content`, not `structuredContent` at top level
    - Downstream consumers (le-chat, etc.) need structuredContent/isError/_meta via metadata

    SYNC: Keep in sync with Harmattan (orchestrator) for harmonized tool result processing.
    """

    content: List[ConnectorToolCallResponseContentTypedDict]
    metadata: NotRequired[Nullable[ConnectorToolCallMetadataTypedDict]]


class ConnectorToolCallResponse(BaseModel):
    r"""Response from calling an MCP tool.

    We override mcp_types.CallToolResult because:
    - Models only support `content`, not `structuredContent` at top level
    - Downstream consumers (le-chat, etc.) need structuredContent/isError/_meta via metadata

    SYNC: Keep in sync with Harmattan (orchestrator) for harmonized tool result processing.
    """

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    content: List[ConnectorToolCallResponseContent]

    metadata: OptionalNullable[ConnectorToolCallMetadata] = UNSET

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["metadata"]
        nullable_fields = ["metadata"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        for k, v in serialized.items():
            m[k] = v

        return m
