"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 9eb5a261f4a3

from __future__ import annotations
from .logicalexpression import LogicalExpression, LogicalExpressionTypedDict
from .toolproperties import ToolProperties, ToolPropertiesTypedDict
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


RequiresConfirmationTypedDict = TypeAliasType(
    "RequiresConfirmationTypedDict",
    Union[ToolPropertiesTypedDict, LogicalExpressionTypedDict, List[str]],
)


RequiresConfirmation = TypeAliasType(
    "RequiresConfirmation", Union[ToolProperties, LogicalExpression, List[str]]
)


IncludeTypedDict = TypeAliasType(
    "IncludeTypedDict",
    Union[ToolPropertiesTypedDict, LogicalExpressionTypedDict, List[str]],
)


Include = TypeAliasType("Include", Union[ToolProperties, LogicalExpression, List[str]])


ExcludeTypedDict = TypeAliasType(
    "ExcludeTypedDict",
    Union[ToolPropertiesTypedDict, LogicalExpressionTypedDict, List[str]],
)


Exclude = TypeAliasType("Exclude", Union[ToolProperties, LogicalExpression, List[str]])


class ConnectorToolsConfigurationTypedDict(TypedDict):
    requires_confirmation: NotRequired[Nullable[RequiresConfirmationTypedDict]]
    include: NotRequired[Nullable[IncludeTypedDict]]
    exclude: NotRequired[Nullable[ExcludeTypedDict]]


class ConnectorToolsConfiguration(BaseModel):
    requires_confirmation: OptionalNullable[RequiresConfirmation] = UNSET

    include: OptionalNullable[Include] = UNSET

    exclude: OptionalNullable[Exclude] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["requires_confirmation", "include", "exclude"])
        nullable_fields = set(["requires_confirmation", "include", "exclude"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
