"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 27ada745e6ad

from __future__ import annotations
from .completionargs import CompletionArgs, CompletionArgsTypedDict
from .conversationinputs import ConversationInputs, ConversationInputsTypedDict
from .toolcallconfirmation import ToolCallConfirmation, ToolCallConfirmationTypedDict
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


ConversationAppendStreamRequestHandoffExecution = Literal[
    "client",
    "server",
]


class ConversationAppendStreamRequestTypedDict(TypedDict):
    inputs: NotRequired[ConversationInputsTypedDict]
    stream: NotRequired[bool]
    store: NotRequired[bool]
    r"""Whether to store the results into our servers or not."""
    handoff_execution: NotRequired[ConversationAppendStreamRequestHandoffExecution]
    completion_args: NotRequired[CompletionArgsTypedDict]
    r"""White-listed arguments from the completion API"""
    tool_confirmations: NotRequired[Nullable[List[ToolCallConfirmationTypedDict]]]


class ConversationAppendStreamRequest(BaseModel):
    inputs: Optional[ConversationInputs] = None

    stream: Optional[bool] = True

    store: Optional[bool] = True
    r"""Whether to store the results into our servers or not."""

    handoff_execution: Optional[ConversationAppendStreamRequestHandoffExecution] = (
        "server"
    )

    completion_args: Optional[CompletionArgs] = None
    r"""White-listed arguments from the completion API"""

    tool_confirmations: OptionalNullable[List[ToolCallConfirmation]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "inputs",
            "stream",
            "store",
            "handoff_execution",
            "completion_args",
            "tool_confirmations",
        ]
        nullable_fields = ["tool_confirmations"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
