"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 8c8b08d853f6

from __future__ import annotations
from .agenthandoffdoneevent import AgentHandoffDoneEvent, AgentHandoffDoneEventTypedDict
from .agenthandoffstartedevent import (
    AgentHandoffStartedEvent,
    AgentHandoffStartedEventTypedDict,
)
from .functioncallevent import FunctionCallEvent, FunctionCallEventTypedDict
from .messageoutputevent import MessageOutputEvent, MessageOutputEventTypedDict
from .responsedoneevent import ResponseDoneEvent, ResponseDoneEventTypedDict
from .responseerrorevent import ResponseErrorEvent, ResponseErrorEventTypedDict
from .responsestartedevent import ResponseStartedEvent, ResponseStartedEventTypedDict
from .ssetypes import SSETypes
from .toolexecutiondeltaevent import (
    ToolExecutionDeltaEvent,
    ToolExecutionDeltaEventTypedDict,
)
from .toolexecutiondoneevent import (
    ToolExecutionDoneEvent,
    ToolExecutionDoneEventTypedDict,
)
from .toolexecutionstartedevent import (
    ToolExecutionStartedEvent,
    ToolExecutionStartedEventTypedDict,
)
from mistralai.client.types import BaseModel
from mistralai.client.utils import validate_open_enum
from pydantic import Field
from pydantic.functional_validators import PlainValidator
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


ConversationEventsDataTypedDict = TypeAliasType(
    "ConversationEventsDataTypedDict",
    Union[
        ResponseStartedEventTypedDict,
        ResponseDoneEventTypedDict,
        ResponseErrorEventTypedDict,
        ToolExecutionDeltaEventTypedDict,
        ToolExecutionDoneEventTypedDict,
        AgentHandoffStartedEventTypedDict,
        AgentHandoffDoneEventTypedDict,
        ToolExecutionStartedEventTypedDict,
        MessageOutputEventTypedDict,
        FunctionCallEventTypedDict,
    ],
)


ConversationEventsData = Annotated[
    Union[
        AgentHandoffDoneEvent,
        AgentHandoffStartedEvent,
        ResponseDoneEvent,
        ResponseErrorEvent,
        ResponseStartedEvent,
        FunctionCallEvent,
        MessageOutputEvent,
        ToolExecutionDeltaEvent,
        ToolExecutionDoneEvent,
        ToolExecutionStartedEvent,
    ],
    Field(discriminator="type"),
]


class ConversationEventsTypedDict(TypedDict):
    event: SSETypes
    r"""Server side events sent when streaming a conversation response."""
    data: ConversationEventsDataTypedDict


class ConversationEvents(BaseModel):
    event: Annotated[SSETypes, PlainValidator(validate_open_enum(False))]
    r"""Server side events sent when streaming a conversation response."""

    data: ConversationEventsData
