"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 80cc6fb316f9

from __future__ import annotations
from .authenticationconfiguration import (
    AuthenticationConfiguration,
    AuthenticationConfigurationTypedDict,
)
from .outboundauthenticationtype import OutboundAuthenticationType
from mistralai.client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CredentialsResponseTypedDict(TypedDict):
    credentials: List[AuthenticationConfigurationTypedDict]
    connector_preset_credentials_for_auth: NotRequired[List[OutboundAuthenticationType]]


class CredentialsResponse(BaseModel):
    credentials: List[AuthenticationConfiguration]

    connector_preset_credentials_for_auth: Optional[
        List[OutboundAuthenticationType]
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["connector_preset_credentials_for_auth"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
