"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 0143a2facd40

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class DataCaptureExtractAvailableModelsTypedDict(TypedDict):
    model_names: List[str]


class DataCaptureExtractAvailableModels(BaseModel):
    model_names: List[str]
