"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 7e930f044bea

from __future__ import annotations
from .capturereason import CaptureReason
from datetime import datetime
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Dict, List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


DataCaptureExtractJobInDatacaptureSourceType = Literal[
    "api",
    "lechat",
]


class DataCaptureExtractJobInTypedDict(TypedDict):
    organization_uuid: NotRequired[Nullable[str]]
    model: NotRequired[Nullable[str]]
    start_date: NotRequired[Nullable[datetime]]
    end_date: NotRequired[Nullable[datetime]]
    data_source: NotRequired[DataCaptureExtractJobInDatacaptureSourceType]
    capture_reasons: NotRequired[Nullable[List[CaptureReason]]]
    metadata: NotRequired[Nullable[Dict[str, str]]]
    timeout_hours: NotRequired[int]


class DataCaptureExtractJobIn(BaseModel):
    organization_uuid: OptionalNullable[str] = UNSET

    model: OptionalNullable[str] = UNSET

    start_date: OptionalNullable[datetime] = UNSET

    end_date: OptionalNullable[datetime] = UNSET

    data_source: Optional[DataCaptureExtractJobInDatacaptureSourceType] = "api"

    capture_reasons: OptionalNullable[List[CaptureReason]] = UNSET

    metadata: OptionalNullable[Dict[str, str]] = UNSET

    timeout_hours: Optional[int] = 48

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "organization_uuid",
                "model",
                "start_date",
                "end_date",
                "data_source",
                "capture_reasons",
                "metadata",
                "timeout_hours",
            ]
        )
        nullable_fields = set(
            [
                "organization_uuid",
                "model",
                "start_date",
                "end_date",
                "capture_reasons",
                "metadata",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
