"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing_extensions import TypedDict


class DatasetImportResultTypedDict(TypedDict):
    r"""Source-agnostic counts for a completed dataset import."""

    requested_record_count: int
    imported_record_count: int
    skipped_record_count: int


class DatasetImportResult(BaseModel):
    r"""Source-agnostic counts for a completed dataset import."""

    requested_record_count: int

    imported_record_count: int

    skipped_record_count: int
