"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: af0a5d45a782

from __future__ import annotations
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from mistralai.client.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class DeploymentK8sBackendSpecTypedDict(TypedDict):
    r"""Worker configuration for the Kubernetes backend."""

    type: Literal["kubernetes"]
    entrypoint: NotRequired[Nullable[str]]
    r"""Either a 'module:function' reference (e.g. 'worker:main') or a '.py' script path relative to 'working_dir'."""
    working_dir: NotRequired[Nullable[str]]
    r"""Path in the repo holding the worker's pyproject.toml, for monorepo layouts. Leave empty for single-package repos."""


class DeploymentK8sBackendSpec(BaseModel):
    r"""Worker configuration for the Kubernetes backend."""

    type: Annotated[
        Annotated[Literal["kubernetes"], AfterValidator(validate_const("kubernetes"))],
        pydantic.Field(alias="type"),
    ] = "kubernetes"

    entrypoint: OptionalNullable[str] = UNSET
    r"""Either a 'module:function' reference (e.g. 'worker:main') or a '.py' script path relative to 'working_dir'."""

    working_dir: OptionalNullable[str] = UNSET
    r"""Path in the repo holding the worker's pyproject.toml, for monorepo layouts. Leave empty for single-package repos."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["entrypoint", "working_dir"])
        nullable_fields = set(["entrypoint", "working_dir"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    DeploymentK8sBackendSpec.model_rebuild()
except NameError:
    pass
