"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 29dddd42d9cc

from __future__ import annotations
from .deploymentworkerresponse import (
    DeploymentWorkerResponse,
    DeploymentWorkerResponseTypedDict,
)
from mistralai.client.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class DeploymentWorkerListResponseTypedDict(TypedDict):
    workers: List[DeploymentWorkerResponseTypedDict]
    r"""Workers registered for the deployment"""
    next_cursor: Nullable[str]
    r"""Cursor for the next page of results"""


class DeploymentWorkerListResponse(BaseModel):
    workers: List[DeploymentWorkerResponse]
    r"""Workers registered for the deployment"""

    next_cursor: Nullable[str]
    r"""Cursor for the next page of results"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
