"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 97955ebc2eb9

from __future__ import annotations
from mistralai.client.types import UnrecognizedStr
from typing import Literal, Union


EncodedPayloadOptions = Union[
    Literal[
        "offloaded",
        "encrypted",
        "encrypted-partial",
    ],
    UnrecognizedStr,
]
