"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .evaluationrunoutputrecordv2 import (
    EvaluationRunOutputRecordV2,
    EvaluationRunOutputRecordV2TypedDict,
)
from datetime import datetime
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Any
from typing_extensions import NotRequired, TypedDict


class EvaluationRunRecordV2ResponseTypedDict(TypedDict):
    id: str
    created_at: datetime
    updated_at: datetime
    deleted_at: Nullable[datetime]
    input: Any
    dataset_record_id: NotRequired[Nullable[str]]
    output_record: NotRequired[Nullable[EvaluationRunOutputRecordV2TypedDict]]


class EvaluationRunRecordV2Response(BaseModel):
    id: str

    created_at: datetime

    updated_at: datetime

    deleted_at: Nullable[datetime]

    input: Any

    dataset_record_id: OptionalNullable[str] = UNSET

    output_record: OptionalNullable[EvaluationRunOutputRecordV2] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["dataset_record_id", "output_record"])
        nullable_fields = set(["deleted_at", "dataset_record_id", "output_record"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
