"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 4d9c138d60b6

from __future__ import annotations
from .paginatedresult_evaluationrecord_ import (
    PaginatedResultEvaluationRecord,
    PaginatedResultEvaluationRecordTypedDict,
)
from mistralai.client.types import BaseModel
from typing_extensions import TypedDict


class EvaluationRecordsTypedDict(TypedDict):
    records: PaginatedResultEvaluationRecordTypedDict


class EvaluationRecords(BaseModel):
    records: PaginatedResultEvaluationRecord
