"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, TypedDict


class EvaluationCategoricalResultSpecTypedDict(TypedDict):
    labels: List[str]
    type: Literal["categorical"]


class EvaluationCategoricalResultSpec(BaseModel):
    labels: List[str]

    type: Annotated[
        Annotated[
            Literal["categorical"], AfterValidator(validate_const("categorical"))
        ],
        pydantic.Field(alias="type"),
    ] = "categorical"


try:
    EvaluationCategoricalResultSpec.model_rebuild()
except NameError:
    pass
