"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class EvaluationBooleanResultSpecTypedDict(TypedDict):
    type: Literal["boolean"]


class EvaluationBooleanResultSpec(BaseModel):
    type: Annotated[
        Annotated[Literal["boolean"], AfterValidator(validate_const("boolean"))],
        pydantic.Field(alias="type"),
    ] = "boolean"


try:
    EvaluationBooleanResultSpec.model_rebuild()
except NameError:
    pass
