"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mistralai.client.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class EvaluationV2TypedDict(TypedDict):
    id: str
    created_at: datetime
    updated_at: datetime
    deleted_at: Nullable[datetime]
    workspace_id: str
    creator_id: str
    project_id: str
    name: str
    slug: str
    description: Nullable[str]
    tags: List[str]
    metadata: Dict[str, Any]
    is_favorite: NotRequired[bool]


class EvaluationV2(BaseModel):
    id: str

    created_at: datetime

    updated_at: datetime

    deleted_at: Nullable[datetime]

    workspace_id: str

    creator_id: str

    project_id: str

    name: str

    slug: str

    description: Nullable[str]

    tags: List[str]

    metadata: Annotated[Dict[str, Any], pydantic.Field(alias="metadata_")]

    is_favorite: Optional[bool] = False

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["is_favorite"])
        nullable_fields = set(["deleted_at", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    EvaluationV2.model_rebuild()
except NameError:
    pass
