"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .classificationstatisticspec import (
    ClassificationStatisticSpec,
    ClassificationStatisticSpecTypedDict,
)
from .goalspec import GoalSpec, GoalSpecTypedDict
from .percentilestatisticspec import (
    PercentileStatisticSpec,
    PercentileStatisticSpecTypedDict,
)
from .simplenumericstatisticspec import (
    SimpleNumericStatisticSpec,
    SimpleNumericStatisticSpecTypedDict,
)
from datetime import datetime
from functools import partial
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from mistralai.client.utils.unions import parse_open_union
from pydantic import ConfigDict, model_serializer
from pydantic.functional_validators import BeforeValidator
from typing import Any, List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


StatisticTypedDict = TypeAliasType(
    "StatisticTypedDict",
    Union[
        SimpleNumericStatisticSpecTypedDict,
        PercentileStatisticSpecTypedDict,
        ClassificationStatisticSpecTypedDict,
    ],
)


class UnknownStatistic(BaseModel):
    r"""A Statistic variant the SDK doesn't recognize. Preserves the raw payload."""

    kind: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_STATISTIC_VARIANTS: dict[str, Any] = {
    "avg": SimpleNumericStatisticSpec,
    "count": SimpleNumericStatisticSpec,
    "f1": ClassificationStatisticSpec,
    "max": SimpleNumericStatisticSpec,
    "min": SimpleNumericStatisticSpec,
    "percentile": PercentileStatisticSpec,
    "precision": ClassificationStatisticSpec,
    "recall": ClassificationStatisticSpec,
    "std": SimpleNumericStatisticSpec,
    "sum": SimpleNumericStatisticSpec,
}


Statistic = Annotated[
    Union[
        SimpleNumericStatisticSpec,
        SimpleNumericStatisticSpec,
        ClassificationStatisticSpec,
        SimpleNumericStatisticSpec,
        SimpleNumericStatisticSpec,
        PercentileStatisticSpec,
        ClassificationStatisticSpec,
        ClassificationStatisticSpec,
        SimpleNumericStatisticSpec,
        SimpleNumericStatisticSpec,
        UnknownStatistic,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="kind",
            variants=_STATISTIC_VARIANTS,
            unknown_cls=UnknownStatistic,
            union_name="Statistic",
        )
    ),
]


EvaluatorV2Direction = Union[
    Literal[
        "maximize",
        "minimize",
    ],
    UnrecognizedStr,
]


class EvaluatorV2TypedDict(TypedDict):
    id: str
    created_at: datetime
    updated_at: datetime
    deleted_at: Nullable[datetime]
    name: str
    description: Nullable[str]
    tags: List[str]
    num_scores: int
    goal: NotRequired[Nullable[GoalSpecTypedDict]]
    aggregate_goal: NotRequired[Nullable[GoalSpecTypedDict]]
    statistics: NotRequired[Nullable[List[StatisticTypedDict]]]
    weight: NotRequired[float]
    direction: NotRequired[Nullable[EvaluatorV2Direction]]
    min_value: NotRequired[Nullable[float]]
    max_value: NotRequired[Nullable[float]]


class EvaluatorV2(BaseModel):
    id: str

    created_at: datetime

    updated_at: datetime

    deleted_at: Nullable[datetime]

    name: str

    description: Nullable[str]

    tags: List[str]

    num_scores: int

    goal: OptionalNullable[GoalSpec] = UNSET

    aggregate_goal: OptionalNullable[GoalSpec] = UNSET

    statistics: OptionalNullable[List[Statistic]] = UNSET

    weight: Optional[float] = 1

    direction: OptionalNullable[EvaluatorV2Direction] = UNSET

    min_value: OptionalNullable[float] = UNSET

    max_value: OptionalNullable[float] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "goal",
                "aggregate_goal",
                "statistics",
                "weight",
                "direction",
                "min_value",
                "max_value",
            ]
        )
        nullable_fields = set(
            [
                "deleted_at",
                "description",
                "goal",
                "aggregate_goal",
                "statistics",
                "direction",
                "min_value",
                "max_value",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
