"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: bbea7a89b60a

from __future__ import annotations
from .executecommandrequest import ExecuteCommandRequest, ExecuteCommandRequestTypedDict
from mistralai.client.types import BaseModel
from mistralai.client.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ExecuteCommandV1SandboxesSandboxIDExecutePostRequestTypedDict(TypedDict):
    sandbox_id: str
    execute_command_request: ExecuteCommandRequestTypedDict


class ExecuteCommandV1SandboxesSandboxIDExecutePostRequest(BaseModel):
    sandbox_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    execute_command_request: Annotated[
        ExecuteCommandRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
