"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: b74b57603a4c

from __future__ import annotations
from .basetaskstatus import BaseTaskStatus
from mistralai.client.types import BaseModel
from mistralai.client.utils import validate_open_enum
from pydantic.functional_validators import PlainValidator
from typing_extensions import Annotated, TypedDict


class FetchCampaignStatusResponseTypedDict(TypedDict):
    status: BaseTaskStatus


class FetchCampaignStatusResponse(BaseModel):
    status: Annotated[BaseTaskStatus, PlainValidator(validate_open_enum(False))]
