"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .recordsortfield import RecordSortField
from .sortdirection import SortDirection
from mistralai.client.types import BaseModel, UNSET_SENTINEL
from mistralai.client.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FieldSortInputTypedDict(TypedDict):
    field: RecordSortField
    kind: Literal["field"]
    direction: NotRequired[SortDirection]


class FieldSortInput(BaseModel):
    field: RecordSortField

    kind: Annotated[
        Annotated[Literal["field"], AfterValidator(validate_const("field"))],
        pydantic.Field(alias="kind"),
    ] = "field"

    direction: Optional[SortDirection] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["direction"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    FieldSortInput.model_rebuild()
except NameError:
    pass
