"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 11a670fa3b71

from __future__ import annotations
from enum import Enum
from mistralai.client import utils


class FileVisibility(str, Enum, metaclass=utils.OpenEnumMeta):
    WORKSPACE = "workspace"
    USER = "user"
