"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: cb775bc63ffd

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetScheduleV1WorkflowsSchedulesScheduleIDGetRequestTypedDict(TypedDict):
    schedule_id: str


class GetScheduleV1WorkflowsSchedulesScheduleIDGetRequest(BaseModel):
    schedule_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
