"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 097af37374fd

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetWorkflowV1WorkflowsWorkflowIdentifierGetRequestTypedDict(TypedDict):
    workflow_identifier: str


class GetWorkflowV1WorkflowsWorkflowIdentifierGetRequest(BaseModel):
    workflow_identifier: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
