"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: e08825b431bc

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetServiceAccountV1ServiceAccountsServiceAccountIDGetRequestTypedDict(TypedDict):
    service_account_id: str


class GetServiceAccountV1ServiceAccountsServiceAccountIDGetRequest(BaseModel):
    service_account_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
