"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 36957d0f73aa

from __future__ import annotations
from .searchchatcompletioneventsrequest import (
    SearchChatCompletionEventsRequest,
    SearchChatCompletionEventsRequestTypedDict,
)
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from mistralai.client.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetChatCompletionEventsV1ObservabilityChatCompletionEventsSearchPostRequestTypedDict(
    TypedDict
):
    search_chat_completion_events_request: SearchChatCompletionEventsRequestTypedDict
    page_size: NotRequired[int]
    cursor: NotRequired[Nullable[str]]


class GetChatCompletionEventsV1ObservabilityChatCompletionEventsSearchPostRequest(
    BaseModel
):
    search_chat_completion_events_request: Annotated[
        SearchChatCompletionEventsRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50

    cursor: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["page_size", "cursor"]
        nullable_fields = ["cursor"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
