"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 2c601dec1463

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetSandboxV1SandboxesSandboxIDGetRequestTypedDict(TypedDict):
    sandbox_id: str


class GetSandboxV1SandboxesSandboxIDGetRequest(BaseModel):
    sandbox_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
