"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 5d6df36b14ff

from __future__ import annotations
from datetime import datetime
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from mistralai.client.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


GetDeploymentLogsOrder = Literal[
    "asc",
    "desc",
]
r"""First-page sort order: 'asc' (oldest first) or 'desc'. Ignored when `cursor` is set."""


class GetDeploymentLogsRequestTypedDict(TypedDict):
    name: str
    worker_name: NotRequired[Nullable[str]]
    r"""Filter logs by worker name"""
    workflow_name: NotRequired[Nullable[str]]
    r"""Filter logs by workflow name"""
    after: NotRequired[Nullable[datetime]]
    r"""Only return logs at or after this timestamp"""
    before: NotRequired[Nullable[datetime]]
    r"""Only return logs before this timestamp"""
    order: NotRequired[GetDeploymentLogsOrder]
    r"""First-page sort order: 'asc' (oldest first) or 'desc'. Ignored when `cursor` is set."""
    cursor: NotRequired[Nullable[str]]
    r"""Pagination cursor from a previous response's `next_cursor`; carries the window and order"""
    limit: NotRequired[int]
    r"""Maximum number of logs to return"""


class GetDeploymentLogsRequest(BaseModel):
    name: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    worker_name: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Filter logs by worker name"""

    workflow_name: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Filter logs by workflow name"""

    after: Annotated[
        OptionalNullable[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Only return logs at or after this timestamp"""

    before: Annotated[
        OptionalNullable[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Only return logs before this timestamp"""

    order: Annotated[
        Optional[GetDeploymentLogsOrder],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "asc"
    r"""First-page sort order: 'asc' (oldest first) or 'desc'. Ignored when `cursor` is set."""

    cursor: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Pagination cursor from a previous response's `next_cursor`; carries the window and order"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50
    r"""Maximum number of logs to return"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "worker_name",
                "workflow_name",
                "after",
                "before",
                "order",
                "cursor",
                "limit",
            ]
        )
        nullable_fields = set(
            ["worker_name", "workflow_name", "after", "before", "cursor"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
