"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: cc90b0975f3f

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetIndexV1RagManagedIndexesIndexNameGetRequestTypedDict(TypedDict):
    index_name: str


class GetIndexV1RagManagedIndexesIndexNameGetRequest(BaseModel):
    index_name: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
