"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: e1b91c8a87e6

from __future__ import annotations
from .connector import Connector, ConnectorTypedDict
from .connectorsqueryfilters import (
    ConnectorsQueryFilters,
    ConnectorsQueryFiltersTypedDict,
)
from .paginatedconnectors_connector_ import (
    PaginatedConnectorsConnector,
    PaginatedConnectorsConnectorTypedDict,
)
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from mistralai.client.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class GetAllInternalV1InternalConnectorsGetRequestTypedDict(TypedDict):
    query_filters: NotRequired[ConnectorsQueryFiltersTypedDict]
    cursor: NotRequired[Nullable[str]]
    page: NotRequired[int]
    page_size: NotRequired[int]


class GetAllInternalV1InternalConnectorsGetRequest(BaseModel):
    query_filters: Annotated[
        Optional[ConnectorsQueryFilters],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    cursor: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 100

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["query_filters", "cursor", "page", "page_size"])
        nullable_fields = set(["cursor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


ResponseGetAllInternalV1InternalConnectorsGetTypedDict = TypeAliasType(
    "ResponseGetAllInternalV1InternalConnectorsGetTypedDict",
    Union[PaginatedConnectorsConnectorTypedDict, List[ConnectorTypedDict]],
)
r"""Successful Response"""


ResponseGetAllInternalV1InternalConnectorsGet = TypeAliasType(
    "ResponseGetAllInternalV1InternalConnectorsGet",
    Union[PaginatedConnectorsConnector, List[Connector]],
)
r"""Successful Response"""
