"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 06a036082c59

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import FieldMetadata, PathParamMetadata
from typing import Literal
from typing_extensions import Annotated, TypedDict


GetIndexSummaryV1RagIndexesIndexIndexIDSummaryFieldLanguageGetLanguage = Literal[
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt_br",
    "pl",
    "ar",
    "nl",
]


class GetIndexSummaryV1RagIndexesIndexIndexIDSummaryFieldLanguageGetRequestTypedDict(
    TypedDict
):
    index_id: str
    language: GetIndexSummaryV1RagIndexesIndexIndexIDSummaryFieldLanguageGetLanguage


class GetIndexSummaryV1RagIndexesIndexIndexIDSummaryFieldLanguageGetRequest(BaseModel):
    index_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    language: Annotated[
        GetIndexSummaryV1RagIndexesIndexIndexIDSummaryFieldLanguageGetLanguage,
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
