"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 88b00f5b6d4d

from __future__ import annotations
from .getdeploymentsummariesresponsevespaindex import (
    GetDeploymentSummariesResponseVespaIndex,
    GetDeploymentSummariesResponseVespaIndexTypedDict,
)
from mistralai.client.types import BaseModel
from mistralai.client.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, TypedDict


class GetDeploymentSummariesResponseVespaDeploymentTypedDict(TypedDict):
    indexes: List[GetDeploymentSummariesResponseVespaIndexTypedDict]
    type: Literal["vespa"]


class GetDeploymentSummariesResponseVespaDeployment(BaseModel):
    indexes: List[GetDeploymentSummariesResponseVespaIndex]

    type: Annotated[
        Annotated[Literal["vespa"], AfterValidator(validate_const("vespa"))],
        pydantic.Field(alias="type"),
    ] = "vespa"


try:
    GetDeploymentSummariesResponseVespaDeployment.model_rebuild()
except NameError:
    pass
