"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: f692ec4c609a

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class GetGroupedEvaluationRecordsInSchemaTypedDict(TypedDict):
    evaluation_run_ids: List[str]


class GetGroupedEvaluationRecordsInSchema(BaseModel):
    evaluation_run_ids: List[str]
