"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: e93e67a4d749

from __future__ import annotations
from .feedresultgetlog import FeedResultGetLog, FeedResultGetLogTypedDict
from mistralai.client.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class GetLogsTypedDict(TypedDict):
    feed_result_get_log: FeedResultGetLogTypedDict


class GetLogs(BaseModel):
    feed_result_get_log: Annotated[FeedResultGetLog, pydantic.Field(alias="logs")]
