"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 91934f70cd68

from __future__ import annotations
from .feedresultgetspanevaluation import (
    FeedResultGetSpanEvaluation,
    FeedResultGetSpanEvaluationTypedDict,
)
from mistralai.client.types import BaseModel
from typing_extensions import TypedDict


class GetSpanEvaluationsTypedDict(TypedDict):
    span_evaluations: FeedResultGetSpanEvaluationTypedDict


class GetSpanEvaluations(BaseModel):
    span_evaluations: FeedResultGetSpanEvaluation
