"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 9a63e248e0d3

from __future__ import annotations
from .schemafieldindex import SchemaFieldIndex
from .schemafieldstorage import SchemaFieldStorage
from .schemafieldtype import SchemaFieldType
from mistralai.client.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class GetSearchIndexSchemaDetailResponseFieldTypedDict(TypedDict):
    name: str
    type: SchemaFieldType
    storage: SchemaFieldStorage
    index_type: Nullable[SchemaFieldIndex]


class GetSearchIndexSchemaDetailResponseField(BaseModel):
    name: str

    type: SchemaFieldType

    storage: SchemaFieldStorage

    index_type: Nullable[SchemaFieldIndex]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
