"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 81804f477af7

from __future__ import annotations
from .otelfielddefinition import OtelFieldDefinition, OtelFieldDefinitionTypedDict
from mistralai.client.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class GetSpanFieldsTypedDict(TypedDict):
    field_definitions: List[OtelFieldDefinitionTypedDict]


class GetSpanFields(BaseModel):
    field_definitions: List[OtelFieldDefinition]
