"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 4bc83ce18378

from __future__ import annotations
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from mistralai.client.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GithubRepositoryTypedDict(TypedDict):
    name: str
    owner: str
    commit_id: str
    type: Literal["github"]
    ref: NotRequired[Nullable[str]]
    weight: NotRequired[float]


class GithubRepository(BaseModel):
    name: str

    owner: str

    commit_id: str

    type: Annotated[
        Annotated[Literal["github"], AfterValidator(validate_const("github"))],
        pydantic.Field(alias="type"),
    ] = "github"

    ref: OptionalNullable[str] = UNSET

    weight: Optional[float] = 1

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ref", "weight"])
        nullable_fields = set(["ref"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    GithubRepository.model_rebuild()
except NameError:
    pass
