"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: c1084b549abb

from __future__ import annotations
from mistralai.client.types import UnrecognizedStr
from typing import Literal, Union


ImageDetail = Union[
    Literal[
        "low",
        "auto",
        "high",
    ],
    UnrecognizedStr,
]
