"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: c1084b549abb

from __future__ import annotations
from enum import Enum
from mistralai.client import utils


class ImageDetail(str, Enum, metaclass=utils.OpenEnumMeta):
    LOW = "low"
    AUTO = "auto"
    HIGH = "high"
