"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 6d3ad9f896c7

from __future__ import annotations
from .assistantmessage import AssistantMessage, AssistantMessageTypedDict
from .modality import Modality
from .systemmessage import SystemMessage, SystemMessageTypedDict
from .tool import Tool, ToolTypedDict
from .toolmessage import ToolMessage, ToolMessageTypedDict
from .usermessage import UserMessage, UserMessageTypedDict
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import Field, model_serializer
from typing import List, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


InstructRequestMessageTypedDict = TypeAliasType(
    "InstructRequestMessageTypedDict",
    Union[
        SystemMessageTypedDict,
        UserMessageTypedDict,
        AssistantMessageTypedDict,
        ToolMessageTypedDict,
    ],
)


InstructRequestMessage = Annotated[
    Union[AssistantMessage, SystemMessage, ToolMessage, UserMessage],
    Field(discriminator="role"),
]


class InstructRequestTypedDict(TypedDict):
    messages: List[InstructRequestMessageTypedDict]
    system_prompt: NotRequired[Nullable[str]]
    available_tools: NotRequired[Nullable[List[ToolTypedDict]]]
    truncate_at_max_tokens: NotRequired[Nullable[int]]
    truncate_at_max_image_tokens: NotRequired[Nullable[int]]
    output_modalities: NotRequired[Nullable[List[Modality]]]


class InstructRequest(BaseModel):
    messages: List[InstructRequestMessage]

    system_prompt: OptionalNullable[str] = UNSET

    available_tools: OptionalNullable[List[Tool]] = UNSET

    truncate_at_max_tokens: OptionalNullable[int] = UNSET

    truncate_at_max_image_tokens: OptionalNullable[int] = UNSET

    output_modalities: OptionalNullable[List[Modality]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "system_prompt",
                "available_tools",
                "truncate_at_max_tokens",
                "truncate_at_max_image_tokens",
                "output_modalities",
            ]
        )
        nullable_fields = set(
            [
                "system_prompt",
                "available_tools",
                "truncate_at_max_tokens",
                "truncate_at_max_image_tokens",
                "output_modalities",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
