"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: d0db00c9729a

from __future__ import annotations
from .confirmationoptions import ConfirmationOptions
from .eolienneintegrationconnectionconfig import (
    EolienneIntegrationConnectionConfig,
    EolienneIntegrationConnectionConfigTypedDict,
)
from .functionpermission import FunctionPermission
from .mcpconnectionconfig import MCPConnectionConfig, MCPConnectionConfigTypedDict
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Any, Dict, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


ConnectionConfigTypedDict = TypeAliasType(
    "ConnectionConfigTypedDict",
    Union[EolienneIntegrationConnectionConfigTypedDict, MCPConnectionConfigTypedDict],
)


ConnectionConfig = TypeAliasType(
    "ConnectionConfig", Union[EolienneIntegrationConnectionConfig, MCPConnectionConfig]
)


class IntegrationDataTypedDict(TypedDict):
    id: str
    customer_configuration: NotRequired[Nullable[Dict[str, Any]]]
    customer_secrets: NotRequired[Nullable[Dict[str, Any]]]
    user_configuration: NotRequired[Nullable[Dict[str, Any]]]
    user_secrets: NotRequired[Nullable[Dict[str, Any]]]
    customer_id: NotRequired[Nullable[str]]
    user_id: NotRequired[Nullable[str]]
    connection_config: NotRequired[Nullable[ConnectionConfigTypedDict]]
    ask_confirmation: NotRequired[Nullable[ConfirmationOptions]]
    function_permissions: NotRequired[Nullable[Dict[str, FunctionPermission]]]


class IntegrationData(BaseModel):
    id: str

    customer_configuration: OptionalNullable[Dict[str, Any]] = UNSET

    customer_secrets: OptionalNullable[Dict[str, Any]] = UNSET

    user_configuration: OptionalNullable[Dict[str, Any]] = UNSET

    user_secrets: OptionalNullable[Dict[str, Any]] = UNSET

    customer_id: OptionalNullable[str] = UNSET

    user_id: OptionalNullable[str] = UNSET

    connection_config: OptionalNullable[ConnectionConfig] = UNSET

    ask_confirmation: OptionalNullable[ConfirmationOptions] = UNSET

    function_permissions: OptionalNullable[Dict[str, FunctionPermission]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "customer_configuration",
                "customer_secrets",
                "user_configuration",
                "user_secrets",
                "customer_id",
                "user_id",
                "connection_config",
                "ask_confirmation",
                "function_permissions",
            ]
        )
        nullable_fields = set(
            [
                "customer_configuration",
                "customer_secrets",
                "user_configuration",
                "user_secrets",
                "customer_id",
                "user_id",
                "connection_config",
                "ask_confirmation",
                "function_permissions",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
