"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: d910fd8fe2d6

from __future__ import annotations
from .classifierfinetuningjobdetails import (
    ClassifierFineTuningJobDetails,
    ClassifierFineTuningJobDetailsTypedDict,
)
from .completionfinetuningjobdetails import (
    CompletionFineTuningJobDetails,
    CompletionFineTuningJobDetailsTypedDict,
)
from mistralai.client.types import BaseModel
from mistralai.client.utils import FieldMetadata, PathParamMetadata
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class JobsAPIRoutesFineTuningGetFineTuningJobRequestTypedDict(TypedDict):
    job_id: str
    r"""The ID of the job to analyse."""


class JobsAPIRoutesFineTuningGetFineTuningJobRequest(BaseModel):
    job_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the job to analyse."""


JobsAPIRoutesFineTuningGetFineTuningJobResponseTypedDict = TypeAliasType(
    "JobsAPIRoutesFineTuningGetFineTuningJobResponseTypedDict",
    Union[
        CompletionFineTuningJobDetailsTypedDict, ClassifierFineTuningJobDetailsTypedDict
    ],
)
r"""OK"""


JobsAPIRoutesFineTuningGetFineTuningJobResponse = Annotated[
    Union[ClassifierFineTuningJobDetails, CompletionFineTuningJobDetails],
    Field(discriminator="job_type"),
]
r"""OK"""
