"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 81651291187a

from __future__ import annotations
from .classifierfinetuningjob import (
    ClassifierFineTuningJob,
    ClassifierFineTuningJobTypedDict,
)
from .completionfinetuningjob import (
    CompletionFineTuningJob,
    CompletionFineTuningJobTypedDict,
)
from .legacyjobmetadata import LegacyJobMetadata, LegacyJobMetadataTypedDict
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType


ResponseTypedDict = TypeAliasType(
    "ResponseTypedDict",
    Union[ClassifierFineTuningJobTypedDict, CompletionFineTuningJobTypedDict],
)


Response = Annotated[
    Union[ClassifierFineTuningJob, CompletionFineTuningJob],
    Field(discriminator="JOB_TYPE"),
]


JobsAPIRoutesFineTuningCreateFineTuningJobResponseTypedDict = TypeAliasType(
    "JobsAPIRoutesFineTuningCreateFineTuningJobResponseTypedDict",
    Union[LegacyJobMetadataTypedDict, ResponseTypedDict],
)
r"""OK"""


JobsAPIRoutesFineTuningCreateFineTuningJobResponse = TypeAliasType(
    "JobsAPIRoutesFineTuningCreateFineTuningJobResponse",
    Union[LegacyJobMetadata, Response],
)
r"""OK"""
