"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: b7521bc9a558

from __future__ import annotations
from .encryptedpatchvalue import EncryptedPatchValue, EncryptedPatchValueTypedDict
from mistralai.client.types import BaseModel
from mistralai.client.utils import validate_const
import pydantic
from pydantic import Field
from pydantic.functional_validators import AfterValidator
from typing import Any, Literal, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class JSONPatchRemoveJSONPatchTypedDict(TypedDict):
    path: str
    r"""A JSON Pointer (RFC 6901) identifying the target location within the document. Can be a string path (e.g., '/foo/bar'), '/', '', or an empty list [] for root-level operations."""
    value: Any
    r"""The value to use for the operation"""
    op: Literal["remove"]
    r"""Remove operation"""


class JSONPatchRemoveJSONPatch(BaseModel):
    path: str
    r"""A JSON Pointer (RFC 6901) identifying the target location within the document. Can be a string path (e.g., '/foo/bar'), '/', '', or an empty list [] for root-level operations."""

    value: Any
    r"""The value to use for the operation"""

    op: Annotated[
        Annotated[Literal["remove"], AfterValidator(validate_const("remove"))],
        pydantic.Field(alias="op"),
    ] = "remove"
    r"""Remove operation"""


class JSONPatchReplaceJSONPatchTypedDict(TypedDict):
    path: str
    r"""A JSON Pointer (RFC 6901) identifying the target location within the document. Can be a string path (e.g., '/foo/bar'), '/', '', or an empty list [] for root-level operations."""
    value: Any
    r"""The value to use for the operation"""
    op: Literal["replace"]
    r"""Replace operation"""


class JSONPatchReplaceJSONPatch(BaseModel):
    path: str
    r"""A JSON Pointer (RFC 6901) identifying the target location within the document. Can be a string path (e.g., '/foo/bar'), '/', '', or an empty list [] for root-level operations."""

    value: Any
    r"""The value to use for the operation"""

    op: Annotated[
        Annotated[Literal["replace"], AfterValidator(validate_const("replace"))],
        pydantic.Field(alias="op"),
    ] = "replace"
    r"""Replace operation"""


class JSONPatchAddJSONPatchTypedDict(TypedDict):
    path: str
    r"""A JSON Pointer (RFC 6901) identifying the target location within the document. Can be a string path (e.g., '/foo/bar'), '/', '', or an empty list [] for root-level operations."""
    value: Any
    r"""The value to use for the operation"""
    op: Literal["add"]
    r"""Add operation"""


class JSONPatchAddJSONPatch(BaseModel):
    path: str
    r"""A JSON Pointer (RFC 6901) identifying the target location within the document. Can be a string path (e.g., '/foo/bar'), '/', '', or an empty list [] for root-level operations."""

    value: Any
    r"""The value to use for the operation"""

    op: Annotated[
        Annotated[Literal["add"], AfterValidator(validate_const("add"))],
        pydantic.Field(alias="op"),
    ] = "add"
    r"""Add operation"""


JSONPatchAppendValueTypedDict = TypeAliasType(
    "JSONPatchAppendValueTypedDict", Union[EncryptedPatchValueTypedDict, str]
)
r"""The value to use for the operation. A string to append to the existing value, or an EncryptedPatchValue wrapper when encryption is applied."""


JSONPatchAppendValue = TypeAliasType(
    "JSONPatchAppendValue", Union[EncryptedPatchValue, str]
)
r"""The value to use for the operation. A string to append to the existing value, or an EncryptedPatchValue wrapper when encryption is applied."""


class JSONPatchAppendJSONPatchTypedDict(TypedDict):
    path: str
    r"""A JSON Pointer (RFC 6901) identifying the target location within the document. Can be a string path (e.g., '/foo/bar'), '/', '', or an empty list [] for root-level operations."""
    value: JSONPatchAppendValueTypedDict
    r"""The value to use for the operation. A string to append to the existing value, or an EncryptedPatchValue wrapper when encryption is applied."""
    op: Literal["append"]
    r"""'append' is an extension for efficient string concatenation in streaming scenarios."""


class JSONPatchAppendJSONPatch(BaseModel):
    path: str
    r"""A JSON Pointer (RFC 6901) identifying the target location within the document. Can be a string path (e.g., '/foo/bar'), '/', '', or an empty list [] for root-level operations."""

    value: JSONPatchAppendValue
    r"""The value to use for the operation. A string to append to the existing value, or an EncryptedPatchValue wrapper when encryption is applied."""

    op: Annotated[
        Annotated[Literal["append"], AfterValidator(validate_const("append"))],
        pydantic.Field(alias="op"),
    ] = "append"
    r"""'append' is an extension for efficient string concatenation in streaming scenarios."""


JSONPatchTypedDict = TypeAliasType(
    "JSONPatchTypedDict",
    Union[
        JSONPatchAppendJSONPatchTypedDict,
        JSONPatchAddJSONPatchTypedDict,
        JSONPatchReplaceJSONPatchTypedDict,
        JSONPatchRemoveJSONPatchTypedDict,
    ],
)


JSONPatch = Annotated[
    Union[
        JSONPatchAddJSONPatch,
        JSONPatchAppendJSONPatch,
        JSONPatchRemoveJSONPatch,
        JSONPatchReplaceJSONPatch,
    ],
    Field(discriminator="op"),
]
