"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 6f9c96450465

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing_extensions import TypedDict


class JudgeDefinitionTypedDict(TypedDict):
    model: str
    prompt: str


class JudgeDefinition(BaseModel):
    model: str

    prompt: str
