"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 7cb7eda77353

from __future__ import annotations
from .judgeoutputtype import JudgeOutputType
from mistralai.client.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class JudgeMetadataTypedDict(TypedDict):
    types: List[JudgeOutputType]
    models: List[str]


class JudgeMetadata(BaseModel):
    types: List[JudgeOutputType]

    models: List[str]
