"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 8e28cb9aff1a

from __future__ import annotations
from .paginatedresultchatcompletioneventpreview import (
    PaginatedResultChatCompletionEventPreview,
    PaginatedResultChatCompletionEventPreviewTypedDict,
)
from mistralai.client.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class ListCampaignSelectedEventsResponseTypedDict(TypedDict):
    paginated_result_chat_completion_event_preview: (
        PaginatedResultChatCompletionEventPreviewTypedDict
    )


class ListCampaignSelectedEventsResponse(BaseModel):
    paginated_result_chat_completion_event_preview: Annotated[
        PaginatedResultChatCompletionEventPreview,
        pydantic.Field(alias="completion_events"),
    ]
