"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .library import Library, LibraryTypedDict
from mistralai.client.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ListLibrariesResponseTypedDict(TypedDict):
    data: List[LibraryTypedDict]


class ListLibrariesResponse(BaseModel):
    data: List[Library]
