"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 952ffea71fc7

from __future__ import annotations
from .serviceaccount import ServiceAccount, ServiceAccountTypedDict
from mistralai.client.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ListServiceAccountsResponseTypedDict(TypedDict):
    items: List[ServiceAccountTypedDict]


class ListServiceAccountsResponse(BaseModel):
    items: List[ServiceAccount]
