"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: d5efd40c8c73

from __future__ import annotations
from .promptversion import PromptVersion, PromptVersionTypedDict
from mistralai.client.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListPromptVersionsResponseTypedDict(TypedDict):
    data: NotRequired[List[PromptVersionTypedDict]]


class ListPromptVersionsResponse(BaseModel):
    data: Optional[List[PromptVersion]] = None
