"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 3f207c8f04c8

from __future__ import annotations
from .mcpservericon import MCPServerIcon, MCPServerIconTypedDict
from .promptargument import PromptArgument, PromptArgumentTypedDict
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, List
from typing_extensions import Annotated, NotRequired, TypedDict


class MCPPromptDictStrAnyTypedDict(TypedDict):
    name: str
    title: NotRequired[Nullable[str]]
    description: NotRequired[Nullable[str]]
    arguments: NotRequired[Nullable[List[PromptArgumentTypedDict]]]
    icons: NotRequired[Nullable[List[MCPServerIconTypedDict]]]
    meta: NotRequired[Nullable[Dict[str, Any]]]


class MCPPromptDictStrAny(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    name: str

    title: OptionalNullable[str] = UNSET

    description: OptionalNullable[str] = UNSET

    arguments: OptionalNullable[List[PromptArgument]] = UNSET

    icons: OptionalNullable[List[MCPServerIcon]] = UNSET

    meta: Annotated[OptionalNullable[Dict[str, Any]], pydantic.Field(alias="_meta")] = (
        UNSET
    )

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["title", "description", "arguments", "icons", "_meta"])
        nullable_fields = set(["title", "description", "arguments", "icons", "_meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


try:
    MCPPromptDictStrAny.model_rebuild()
except NameError:
    pass
