"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .systemparamoperator import SystemParamOperator
from mistralai.client.types import BaseModel
from typing import Union
from typing_extensions import TypeAliasType, TypedDict


MetadataFilterValueTypedDict = TypeAliasType(
    "MetadataFilterValueTypedDict", Union[float, str, bool]
)


MetadataFilterValue = TypeAliasType("MetadataFilterValue", Union[float, str, bool])


class MetadataFilterTypedDict(TypedDict):
    key: str
    operator: SystemParamOperator
    value: MetadataFilterValueTypedDict


class MetadataFilter(BaseModel):
    key: str

    operator: SystemParamOperator

    value: MetadataFilterValue
