"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 64d8a422ea29

from __future__ import annotations
from mistralai.client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ModelCapabilitiesTypedDict(TypedDict):
    r"""This is populated by Harmattan, but some fields have a name
    that we don't want to expose in the API.
    """

    completion_chat: NotRequired[bool]
    function_calling: NotRequired[bool]
    reasoning: NotRequired[bool]
    completion_fim: NotRequired[bool]
    fine_tuning: NotRequired[bool]
    vision: NotRequired[bool]
    ocr: NotRequired[bool]
    classification: NotRequired[bool]
    moderation: NotRequired[bool]
    audio: NotRequired[bool]
    audio_transcription: NotRequired[bool]
    audio_transcription_realtime: NotRequired[bool]
    audio_speech: NotRequired[bool]


class ModelCapabilities(BaseModel):
    r"""This is populated by Harmattan, but some fields have a name
    that we don't want to expose in the API.
    """

    completion_chat: Optional[bool] = False

    function_calling: Optional[bool] = False

    reasoning: Optional[bool] = False

    completion_fim: Optional[bool] = False

    fine_tuning: Optional[bool] = False

    vision: Optional[bool] = False

    ocr: Optional[bool] = False

    classification: Optional[bool] = False

    moderation: Optional[bool] = False

    audio: Optional[bool] = False

    audio_transcription: Optional[bool] = False

    audio_transcription_realtime: Optional[bool] = False

    audio_speech: Optional[bool] = False

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "completion_chat",
                "function_calling",
                "reasoning",
                "completion_fim",
                "fine_tuning",
                "vision",
                "ocr",
                "classification",
                "moderation",
                "audio",
                "audio_transcription",
                "audio_transcription_realtime",
                "audio_speech",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
