"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .scalarstatisticvalue import ScalarStatisticValue, ScalarStatisticValueTypedDict
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from mistralai.client.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class NumericStatisticsTypedDict(TypedDict):
    type: Literal["numeric"]
    values: NotRequired[Nullable[List[ScalarStatisticValueTypedDict]]]
    sample_count: NotRequired[int]
    avg: NotRequired[Nullable[float]]
    min: NotRequired[Nullable[float]]
    max: NotRequired[Nullable[float]]
    std: NotRequired[Nullable[float]]
    count: NotRequired[int]


class NumericStatistics(BaseModel):
    type: Annotated[
        Annotated[
            Optional[Literal["numeric"]], AfterValidator(validate_const("numeric"))
        ],
        pydantic.Field(alias="type"),
    ] = "numeric"

    values: OptionalNullable[List[ScalarStatisticValue]] = UNSET

    sample_count: Optional[int] = 0

    avg: OptionalNullable[float] = UNSET

    min: OptionalNullable[float] = UNSET

    max: OptionalNullable[float] = UNSET

    std: OptionalNullable[float] = UNSET

    count: Optional[int] = 0

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["type", "values", "sample_count", "avg", "min", "max", "std", "count"]
        )
        nullable_fields = set(["values", "avg", "min", "max", "std"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    NumericStatistics.model_rebuild()
except NameError:
    pass
