"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: cd49dbf313aa

from __future__ import annotations
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict
from typing_extensions import Annotated, NotRequired, TypedDict


class OAuthFlowTypedDict(TypedDict):
    r"""Configuration details for a supported OAuth Flow"""

    authorization_url: NotRequired[Nullable[str]]
    token_url: NotRequired[Nullable[str]]
    refresh_url: NotRequired[Nullable[str]]
    scopes: NotRequired[Nullable[Dict[str, str]]]


class OAuthFlow(BaseModel):
    r"""Configuration details for a supported OAuth Flow"""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    authorization_url: Annotated[
        OptionalNullable[str], pydantic.Field(alias="authorizationUrl")
    ] = UNSET

    token_url: Annotated[OptionalNullable[str], pydantic.Field(alias="tokenUrl")] = (
        UNSET
    )

    refresh_url: Annotated[
        OptionalNullable[str], pydantic.Field(alias="refreshUrl")
    ] = UNSET

    scopes: OptionalNullable[Dict[str, str]] = UNSET

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["authorizationUrl", "tokenUrl", "refreshUrl", "scopes"])
        nullable_fields = set(["authorizationUrl", "tokenUrl", "refreshUrl", "scopes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


try:
    OAuthFlow.model_rebuild()
except NameError:
    pass
