"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: e20b168770d8

from __future__ import annotations
from .pipelineconfigheader import PipelineConfigHeader, PipelineConfigHeaderTypedDict
from mistralai.client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class OTLPDestinationTypedDict(TypedDict):
    protocol: str
    endpoint: str
    insecure: NotRequired[bool]
    headers: NotRequired[Dict[str, PipelineConfigHeaderTypedDict]]


class OTLPDestination(BaseModel):
    protocol: str

    endpoint: str

    insecure: Optional[bool] = False

    headers: Optional[Dict[str, PipelineConfigHeader]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["insecure", "headers"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
