"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.client.types import UnrecognizedStr
from typing import Literal, Union


PipelineKind = Union[
    Literal[
        "detection-v1",
        "moderation-v1",
        "judge-v1",
        "export-v1",
    ],
    UnrecognizedStr,
]
