"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 88b0ea13ddbc

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PostDatasetImportFromExplorerInSchemaTypedDict(TypedDict):
    completion_event_ids: List[str]


class PostDatasetImportFromExplorerInSchema(BaseModel):
    completion_event_ids: List[str]
