"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 580276cdebc3

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing_extensions import TypedDict


class PostDatasetInSchemaTypedDict(TypedDict):
    name: str
    description: str


class PostDatasetInSchema(BaseModel):
    name: str

    description: str
