"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class ProbabilisticSamplingTypedDict(TypedDict):
    percentage: float
    type: Literal["probabilistic"]


class ProbabilisticSampling(BaseModel):
    percentage: float

    type: Annotated[
        Annotated[
            Literal["probabilistic"], AfterValidator(validate_const("probabilistic"))
        ],
        pydantic.Field(alias="type"),
    ] = "probabilistic"


try:
    ProbabilisticSampling.model_rebuild()
except NameError:
    pass
