"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: c86c2b89e3ce

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PromptVariableTypedDict(TypedDict):
    name: NotRequired[str]
    r"""Stable object name."""


class PromptVariable(BaseModel):
    name: Optional[str] = None
    r"""Stable object name."""
