"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 2a42328ce964

from __future__ import annotations
from .v1versionattributes import V1VersionAttributes, V1VersionAttributesTypedDict
from mistralai.client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PromptsInternalServiceUpdatePromptVersionAttributesBodyTypedDict(TypedDict):
    version_attributes: NotRequired[V1VersionAttributesTypedDict]


class PromptsInternalServiceUpdatePromptVersionAttributesBody(BaseModel):
    version_attributes: Annotated[
        Optional[V1VersionAttributes], pydantic.Field(alias="versionAttributes")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["versionAttributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PromptsInternalServiceUpdatePromptVersionAttributesBody.model_rebuild()
except NameError:
    pass
