"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: ed1ab96e4d47

from __future__ import annotations
from .promptdefinition import PromptDefinition, PromptDefinitionTypedDict
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from mistralai.client.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreatePromptVersionRequestTypedDict(TypedDict):
    definition: PromptDefinitionTypedDict
    r"""Versioned prompt content."""
    notes: NotRequired[Nullable[str]]
    r"""Notes for this version."""
    aliases: NotRequired[List[str]]
    r"""Aliases pointing to this version."""


class CreatePromptVersionRequest(BaseModel):
    definition: PromptDefinition
    r"""Versioned prompt content."""

    notes: OptionalNullable[str] = UNSET
    r"""Notes for this version."""

    aliases: Optional[List[str]] = None
    r"""Aliases pointing to this version."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["notes", "aliases"])
        nullable_fields = set(["notes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class PromptsCreateVersionRequestTypedDict(TypedDict):
    prompt_id: str
    request_body: CreatePromptVersionRequestTypedDict


class PromptsCreateVersionRequest(BaseModel):
    prompt_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        CreatePromptVersionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
