"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: a11aef93fd11

from __future__ import annotations
from typing import Literal


PublicResourceVisibility = Literal[
    "shared_org",
    "shared_workspace",
    "private",
]
r"""Visibility options available to public API callers.

Excludes ``shared_global`` which is reserved for system-owned connectors.
"""
