"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: c187ba1b551d

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class RealtimeTranscriptionInputAudioEndTypedDict(TypedDict):
    type: Literal["input_audio.end"]


class RealtimeTranscriptionInputAudioEnd(BaseModel):
    type: Annotated[
        Annotated[
            Optional[Literal["input_audio.end"]],
            AfterValidator(validate_const("input_audio.end")),
        ],
        pydantic.Field(alias="type"),
    ] = "input_audio.end"
