"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 89c0feb14bcb

from __future__ import annotations
from .schemafielddatatype import SchemaFieldDataType
from .schemafieldindex import SchemaFieldIndex
from .schemafieldrankingtype import SchemaFieldRankingType
from .schemafieldstorage import SchemaFieldStorage
from mistralai.client.types import BaseModel, Nullable, UNSET_SENTINEL
from mistralai.client.utils import validate_open_enum
from pydantic import model_serializer
from pydantic.functional_validators import PlainValidator
from typing_extensions import Annotated, TypedDict


class RegisterSearchIndexRequestVespaSchemaFieldTypedDict(TypedDict):
    name: str
    type: SchemaFieldDataType
    storage: SchemaFieldStorage
    ranking: SchemaFieldRankingType
    index_type: Nullable[SchemaFieldIndex]
    multidimensional: bool


class RegisterSearchIndexRequestVespaSchemaField(BaseModel):
    name: str

    type: Annotated[SchemaFieldDataType, PlainValidator(validate_open_enum(False))]

    storage: Annotated[SchemaFieldStorage, PlainValidator(validate_open_enum(False))]

    ranking: SchemaFieldRankingType

    index_type: Annotated[
        Nullable[SchemaFieldIndex], PlainValidator(validate_open_enum(False))
    ]

    multidimensional: bool

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = []
        nullable_fields = ["index_type"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
