"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 58cbbc423f90

from __future__ import annotations
from mistralai.client.types import UnrecognizedInt
from typing import Literal, Union


ResourceType = Union[
    Literal[
        1,
        2,
        3,
        4,
    ],
    UnrecognizedInt,
]
