"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing_extensions import TypedDict


class RunOptimizationRefTypedDict(TypedDict):
    r"""Typed run→optimization back-ref, derived at read from the optimization_run link.

    Not stored on the run (single source of truth = optimization_run); lets a run row show
    its optimization (id + name) without an extra request per run.
    """

    optimization_id: str
    name: str


class RunOptimizationRef(BaseModel):
    r"""Typed run→optimization back-ref, derived at read from the optimization_run link.

    Not stored on the run (single source of truth = optimization_run); lets a run row show
    its optimization (id + name) without an extra request per run.
    """

    optimization_id: str

    name: str
