"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 6ec367e3cfe5

from __future__ import annotations
from typing import Literal


SchemaFieldStorage = Literal[
    "in_memory",
    "on_disk",
]
