"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 9501fc2b7fa1

from __future__ import annotations
from mistralai.client.types import UnrecognizedStr
from typing import Literal, Union


SchemaFieldIndex = Union[
    Literal[
        "ann",
        "bm25",
        "attribute",
    ],
    UnrecognizedStr,
]
