"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 57923d3e043c

from __future__ import annotations
from .searchhitresponse import SearchHitResponse, SearchHitResponseTypedDict
from mistralai.client.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class SearchResponseTypedDict(TypedDict):
    hits: List[SearchHitResponseTypedDict]


class SearchResponse(BaseModel):
    hits: List[SearchHitResponse]
