"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 26821a9e16a7

from __future__ import annotations
from .spanevaluationsrequest import (
    SpanEvaluationsRequest,
    SpanEvaluationsRequestTypedDict,
)
from datetime import datetime
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from mistralai.client.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SearchLatestSpanEvaluationsV1ObservabilitySpansEvaluationsSearchLatestPostRequestTypedDict(
    TypedDict
):
    span_evaluations_request: SpanEvaluationsRequestTypedDict
    from_: NotRequired[Nullable[datetime]]
    to: NotRequired[Nullable[datetime]]
    page_size: NotRequired[int]
    cursor: NotRequired[Nullable[str]]


class SearchLatestSpanEvaluationsV1ObservabilitySpansEvaluationsSearchLatestPostRequest(
    BaseModel
):
    span_evaluations_request: Annotated[
        SpanEvaluationsRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    from_: Annotated[
        OptionalNullable[datetime],
        pydantic.Field(alias="from"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET

    to: Annotated[
        OptionalNullable[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50

    cursor: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["from", "to", "page_size", "cursor"]
        nullable_fields = ["from", "to", "cursor"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
