"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 098e435f9b95

from __future__ import annotations
from mistralai.client.types import UnrecognizedStr
from typing import Literal, Union


SharingScope = Union[
    Literal[
        "sharing_scope_unspecified",
        "private",
        "workspace",
    ],
    UnrecognizedStr,
]
