"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 0a4f50bb358b

from __future__ import annotations
from .registrysharingscope import RegistrySharingScope
from mistralai.client.types import BaseModel
from mistralai.client.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    validate_open_enum,
)
import pydantic
from pydantic.functional_validators import PlainValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateSkillRequestTypedDict(TypedDict):
    sharing_scope: NotRequired[RegistrySharingScope]


class UpdateSkillRequest(BaseModel):
    sharing_scope: Annotated[
        Annotated[
            Optional[RegistrySharingScope], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="sharingScope"),
    ] = None


class SkillsUpdateRequestTypedDict(TypedDict):
    skill_id: str
    request_body: UpdateSkillRequestTypedDict


class SkillsUpdateRequest(BaseModel):
    skill_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        UpdateSkillRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
