"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 620d89bcbb10

from __future__ import annotations
from .rpcstatus import RPCStatus, RPCStatusTypedDict
from .v1listskillversionsresponse import (
    V1ListSkillVersionsResponse,
    V1ListSkillVersionsResponseTypedDict,
)
from mistralai.client.types import BaseModel
from mistralai.client.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class SkillsListVersionsRequestTypedDict(TypedDict):
    skill_id: str


class SkillsListVersionsRequest(BaseModel):
    skill_id: Annotated[
        str,
        pydantic.Field(alias="skillId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


SkillsListVersionsResponseTypedDict = TypeAliasType(
    "SkillsListVersionsResponseTypedDict",
    Union[V1ListSkillVersionsResponseTypedDict, RPCStatusTypedDict],
)


SkillsListVersionsResponse = TypeAliasType(
    "SkillsListVersionsResponse", Union[V1ListSkillVersionsResponse, RPCStatus]
)
