"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: b3600a24a06d

from __future__ import annotations
from .listskillsresponse import ListSkillsResponse, ListSkillsResponseTypedDict
from mistralai.client.types import BaseModel
from mistralai.client.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import Awaitable, Callable, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class SkillsListRequestTypedDict(TypedDict):
    page_size: NotRequired[int]
    page_token: NotRequired[str]
    alias: NotRequired[str]
    fields: NotRequired[List[str]]


class SkillsListRequest(BaseModel):
    page_size: Annotated[
        Optional[int],
        pydantic.Field(alias="pageSize"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    page_token: Annotated[
        Optional[str],
        pydantic.Field(alias="pageToken"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    alias: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    fields: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None


class SkillsListResponseTypedDict(TypedDict):
    result: ListSkillsResponseTypedDict


class SkillsListResponse(BaseModel):
    next: Union[
        Callable[[], Optional[SkillsListResponse]],
        Callable[[], Awaitable[Optional[SkillsListResponse]]],
    ]

    result: ListSkillsResponse
