"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 1e87cf43e50f

from __future__ import annotations
from .skilldefinition import SkillDefinition, SkillDefinitionTypedDict
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from mistralai.client.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateSkillVersionRequestTypedDict(TypedDict):
    definition: SkillDefinitionTypedDict
    r"""Versioned skill content."""
    notes: NotRequired[Nullable[str]]
    r"""Notes for this version."""
    aliases: NotRequired[List[str]]
    r"""Aliases pointing to this version."""


class CreateSkillVersionRequest(BaseModel):
    definition: SkillDefinition
    r"""Versioned skill content."""

    notes: OptionalNullable[str] = UNSET
    r"""Notes for this version."""

    aliases: Optional[List[str]] = None
    r"""Aliases pointing to this version."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["notes", "aliases"]
        nullable_fields = ["notes"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class SkillsCreateVersionRequestTypedDict(TypedDict):
    skill_id: str
    request_body: CreateSkillVersionRequestTypedDict


class SkillsCreateVersionRequest(BaseModel):
    skill_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        CreateSkillVersionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
