"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: fcee60a4ea0d

from __future__ import annotations
from enum import Enum
from mistralai.client import utils


class Source(str, Enum, metaclass=utils.OpenEnumMeta):
    UPLOAD = "upload"
    REPOSITORY = "repository"
    MISTRAL = "mistral"
