"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 9355a2756b31

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class StepStartedEventTypedDict(TypedDict):
    step_id: str
    query: str
    type: Literal["task.step.started"]


class StepStartedEvent(BaseModel):
    step_id: str

    query: str

    type: Annotated[
        Annotated[
            Literal["task.step.started"],
            AfterValidator(validate_const("task.step.started")),
        ],
        pydantic.Field(alias="type"),
    ] = "task.step.started"


try:
    StepStartedEvent.model_rebuild()
except NameError:
    pass
