"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: c6e21688bc0c

from __future__ import annotations
from mistralai.client.types import BaseModel
from mistralai.client.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class StopDeploymentV1WorkflowsDeploymentsNameStopPostRequestTypedDict(TypedDict):
    name: str


class StopDeploymentV1WorkflowsDeploymentsNameStopPostRequest(BaseModel):
    name: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
