"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 33528845f8f2

from __future__ import annotations
from .executionlogrecord import ExecutionLogRecord, ExecutionLogRecordTypedDict
from .streamerror import StreamError, StreamErrorTypedDict
from datetime import datetime
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from mistralai.client.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    validate_open_enum,
)
from pydantic import model_serializer
from pydantic.functional_validators import PlainValidator
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class StreamWorkflowExecutionLogsRequestTypedDict(TypedDict):
    execution_id: str
    run_id: NotRequired[Nullable[str]]
    r"""Filter logs by workflow run ID"""
    activity_id: NotRequired[Nullable[str]]
    r"""Filter logs by activity ID"""
    after: NotRequired[Nullable[datetime]]
    r"""Start a fresh stream at this timestamp (ignored when resuming via last_event_id)"""
    last_event_id: NotRequired[Nullable[str]]
    r"""Resume from this cursor (a prior response's SSE id)"""


class StreamWorkflowExecutionLogsRequest(BaseModel):
    execution_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    run_id: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Filter logs by workflow run ID"""

    activity_id: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Filter logs by activity ID"""

    after: Annotated[
        OptionalNullable[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Start a fresh stream at this timestamp (ignored when resuming via last_event_id)"""

    last_event_id: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Resume from this cursor (a prior response's SSE id)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["run_id", "activity_id", "after", "last_event_id"]
        nullable_fields = ["run_id", "activity_id", "after", "last_event_id"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


StreamWorkflowExecutionLogsEvent = Union[
    Literal[
        "log",
        "error",
    ],
    UnrecognizedStr,
]


StreamWorkflowExecutionLogsDataTypedDict = TypeAliasType(
    "StreamWorkflowExecutionLogsDataTypedDict",
    Union[StreamErrorTypedDict, ExecutionLogRecordTypedDict],
)


StreamWorkflowExecutionLogsData = TypeAliasType(
    "StreamWorkflowExecutionLogsData", Union[StreamError, ExecutionLogRecord]
)


class StreamWorkflowExecutionLogsResponseBodyTypedDict(TypedDict):
    r"""Stream of Server-Sent Events (SSE): `log` events carry an ExecutionLogRecord; `error` events carry a StreamError payload."""

    event: NotRequired[StreamWorkflowExecutionLogsEvent]
    id: NotRequired[str]
    data: NotRequired[StreamWorkflowExecutionLogsDataTypedDict]


class StreamWorkflowExecutionLogsResponseBody(BaseModel):
    r"""Stream of Server-Sent Events (SSE): `log` events carry an ExecutionLogRecord; `error` events carry a StreamError payload."""

    event: Annotated[
        Optional[StreamWorkflowExecutionLogsEvent],
        PlainValidator(validate_open_enum(False)),
    ] = None

    id: Optional[str] = None

    data: Optional[StreamWorkflowExecutionLogsData] = None
