"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: fcd9710a560b

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing_extensions import TypedDict


class SummaryChunkTypedDict(TypedDict):
    r"""Regular content."""

    content: str


class SummaryChunk(BaseModel):
    r"""Regular content."""

    content: str
