"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: d75dd416f9e3

from __future__ import annotations
from .tempotraceattributearraycontainer import (
    TempoTraceAttributeArrayContainer,
    TempoTraceAttributeArrayContainerTypedDict,
)
from mistralai.client.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class TempoTraceAttributeArrayValueTypedDict(TypedDict):
    array_value: TempoTraceAttributeArrayContainerTypedDict


class TempoTraceAttributeArrayValue(BaseModel):
    array_value: Annotated[
        TempoTraceAttributeArrayContainer, pydantic.Field(alias="arrayValue")
    ]


try:
    TempoTraceAttributeArrayValue.model_rebuild()
except NameError:
    pass
