"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 30d063ab0023

from __future__ import annotations
from mistralai.client.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class TempoTraceAttributeDoubleValueTypedDict(TypedDict):
    double_value: float
    r"""The floating point value of the attribute"""


class TempoTraceAttributeDoubleValue(BaseModel):
    double_value: Annotated[float, pydantic.Field(alias="doubleValue")]
    r"""The floating point value of the attribute"""


try:
    TempoTraceAttributeDoubleValue.model_rebuild()
except NameError:
    pass
