"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 69fcb691327a

from __future__ import annotations
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, Literal, Union
from typing_extensions import Annotated, NotRequired, TypedDict


TaskSupport = Union[
    Literal[
        "forbidden",
        "optional",
        "required",
    ],
    UnrecognizedStr,
]


class ToolExecutionTypedDict(TypedDict):
    r"""Execution-related properties for a tool."""

    task_support: NotRequired[Nullable[TaskSupport]]


class ToolExecution(BaseModel):
    r"""Execution-related properties for a tool."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    task_support: Annotated[
        OptionalNullable[TaskSupport], pydantic.Field(alias="taskSupport")
    ] = UNSET

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["taskSupport"])
        nullable_fields = set(["taskSupport"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


try:
    ToolExecution.model_rebuild()
except NameError:
    pass
