"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 1c9369616b21

from __future__ import annotations
from .logicalexpression import LogicalExpression, LogicalExpressionTypedDict
from .toolproperties import ToolProperties, ToolPropertiesTypedDict
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


RequiresConfirmationTypedDict = TypeAliasType(
    "RequiresConfirmationTypedDict",
    Union[ToolPropertiesTypedDict, LogicalExpressionTypedDict, List[str]],
)


RequiresConfirmation = TypeAliasType(
    "RequiresConfirmation", Union[ToolProperties, LogicalExpression, List[str]]
)


SkipConfirmationTypedDict = TypeAliasType(
    "SkipConfirmationTypedDict",
    Union[ToolPropertiesTypedDict, LogicalExpressionTypedDict, List[str]],
)


SkipConfirmation = TypeAliasType(
    "SkipConfirmation", Union[ToolProperties, LogicalExpression, List[str]]
)


class ToolExecutionConfigurationTypedDict(TypedDict):
    requires_confirmation: NotRequired[Nullable[RequiresConfirmationTypedDict]]
    skip_confirmation: NotRequired[Nullable[SkipConfirmationTypedDict]]
    include: NotRequired[Nullable[List[str]]]
    exclude: NotRequired[Nullable[List[str]]]


class ToolExecutionConfiguration(BaseModel):
    requires_confirmation: OptionalNullable[RequiresConfirmation] = UNSET

    skip_confirmation: OptionalNullable[SkipConfirmation] = UNSET

    include: OptionalNullable[List[str]] = UNSET

    exclude: OptionalNullable[List[str]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["requires_confirmation", "skip_confirmation", "include", "exclude"]
        )
        nullable_fields = set(
            ["requires_confirmation", "skip_confirmation", "include", "exclude"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
