"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: bd45f357a538

from __future__ import annotations
from .conversationpayload import ConversationPayload, ConversationPayloadTypedDict
from mistralai.client.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class UpdateDatasetRecordPayloadRequestTypedDict(TypedDict):
    conversation_payload: ConversationPayloadTypedDict


class UpdateDatasetRecordPayloadRequest(BaseModel):
    conversation_payload: Annotated[
        ConversationPayload, pydantic.Field(alias="payload")
    ]
