"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 8152b78df3c6

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing_extensions import TypedDict


class UpdateSkillSharingScopeResponseTypedDict(TypedDict):
    pass


class UpdateSkillSharingScopeResponse(BaseModel):
    pass
