"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 01740c0031f5

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing_extensions import TypedDict


class UpdatePromptResponseTypedDict(TypedDict):
    pass


class UpdatePromptResponse(BaseModel):
    pass
