"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: ae3a6abea468

from __future__ import annotations
from .agentupdaterequest import AgentUpdateRequest, AgentUpdateRequestTypedDict
from mistralai.client.types import BaseModel
from mistralai.client.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateAgentRequestTypedDict(TypedDict):
    agent_id: str
    agent_update_request: AgentUpdateRequestTypedDict


class UpdateAgentRequest(BaseModel):
    agent_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    agent_update_request: Annotated[
        AgentUpdateRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
