"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 7d9e0649c16e

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing_extensions import TypedDict


class UserOrganizationTypedDict(TypedDict):
    id: str
    r"""The organization's unique identifier."""
    name: str
    r"""The organization's display name."""


class UserOrganization(BaseModel):
    id: str
    r"""The organization's unique identifier."""

    name: str
    r"""The organization's display name."""
