"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: bfdf12cfd6e6

from __future__ import annotations
from .v1attributes import V1Attributes, V1AttributesTypedDict
from .v1skill import V1Skill, V1SkillTypedDict
from .v1versionattributes import V1VersionAttributes, V1VersionAttributesTypedDict
from mistralai.client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V1CreateSkillRequestTypedDict(TypedDict):
    skill: NotRequired[V1SkillTypedDict]
    r"""Per-version content package surfaced to the model."""
    attributes: NotRequired[V1AttributesTypedDict]
    version_attributes: NotRequired[V1VersionAttributesTypedDict]
    name: NotRequired[str]
    r"""Optional human-readable name (immutable after creation, workspace-unique)."""


class V1CreateSkillRequest(BaseModel):
    skill: Optional[V1Skill] = None
    r"""Per-version content package surfaced to the model."""

    attributes: Optional[V1Attributes] = None

    version_attributes: Annotated[
        Optional[V1VersionAttributes], pydantic.Field(alias="versionAttributes")
    ] = None

    name: Optional[str] = None
    r"""Optional human-readable name (immutable after creation, workspace-unique)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["skill", "attributes", "versionAttributes", "name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    V1CreateSkillRequest.model_rebuild()
except NameError:
    pass
