"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 670ebd23a74c

from __future__ import annotations
from datetime import datetime
from mistralai.client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V1VersionMetadataTypedDict(TypedDict):
    created_at: NotRequired[datetime]


class V1VersionMetadata(BaseModel):
    created_at: Annotated[Optional[datetime], pydantic.Field(alias="createdAt")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    V1VersionMetadata.model_rebuild()
except NameError:
    pass
