"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 15df3c7368ab

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing import Any, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


LocTypedDict = TypeAliasType("LocTypedDict", Union[str, int])


Loc = TypeAliasType("Loc", Union[str, int])


class ContextTypedDict(TypedDict):
    pass


class Context(BaseModel):
    pass


class ValidationErrorTypedDict(TypedDict):
    loc: List[LocTypedDict]
    msg: str
    type: str
    input: NotRequired[Any]
    ctx: NotRequired[ContextTypedDict]


class ValidationError(BaseModel):
    loc: List[Loc]

    msg: str

    type: str

    input: Optional[Any] = None

    ctx: Optional[Context] = None
