"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 1ce6ba31e687

from __future__ import annotations
from mistralai.client.types import BaseModel
from typing_extensions import TypedDict


class ValidateJudgeInstructionsInSchemaTypedDict(TypedDict):
    instructions: str


class ValidateJudgeInstructionsInSchema(BaseModel):
    instructions: str
