"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: ee7484f75a7c

from __future__ import annotations
from .vespaschemaresponse import VespaSchemaResponse, VespaSchemaResponseTypedDict
from mistralai.client.types import BaseModel
from mistralai.client.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, TypedDict


class VespaSearchIndexInfoResponseTypedDict(TypedDict):
    k8s_cluster: str
    k8s_namespace: str
    vespa_instance_name: str
    schemas: List[VespaSchemaResponseTypedDict]
    type: Literal["vespa"]


class VespaSearchIndexInfoResponse(BaseModel):
    k8s_cluster: str

    k8s_namespace: str

    vespa_instance_name: str

    schemas: List[VespaSchemaResponse]

    type: Annotated[
        Annotated[Literal["vespa"], AfterValidator(validate_const("vespa"))],
        pydantic.Field(alias="type"),
    ] = "vespa"


try:
    VespaSearchIndexInfoResponse.model_rebuild()
except NameError:
    pass
