"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from mistralai.client.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class WhoamiServiceAccountPrincipalTypedDict(TypedDict):
    r"""Identity of a service-account principal.

    Carries service-account-only fields. Service accounts have no user profile
    (no email or name of a person); ``name`` is the service account's own display
    name. Resolved independently of the authentication mechanism.
    """

    service_account_id: str
    r"""The service account's unique identifier."""
    principal_type: Literal["service_account"]
    r"""Discriminator identifying a service-account principal."""
    name: NotRequired[Nullable[str]]
    r"""The service account's display name, when known."""


class WhoamiServiceAccountPrincipal(BaseModel):
    r"""Identity of a service-account principal.

    Carries service-account-only fields. Service accounts have no user profile
    (no email or name of a person); ``name`` is the service account's own display
    name. Resolved independently of the authentication mechanism.
    """

    service_account_id: str
    r"""The service account's unique identifier."""

    principal_type: Annotated[
        Annotated[
            Literal["service_account"],
            AfterValidator(validate_const("service_account")),
        ],
        pydantic.Field(alias="principal_type"),
    ] = "service_account"
    r"""Discriminator identifying a service-account principal."""

    name: OptionalNullable[str] = UNSET
    r"""The service account's display name, when known."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        nullable_fields = set(["name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    WhoamiServiceAccountPrincipal.model_rebuild()
except NameError:
    pass
