"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 71f9879c69c6

from __future__ import annotations
from .workflowregistrationrefresponse import (
    WorkflowRegistrationRefResponse,
    WorkflowRegistrationRefResponseTypedDict,
)
from mistralai.client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class WorkflowSpecsRegisterResponseTypedDict(TypedDict):
    workflow_registration_ids: List[str]
    r"""List of workflow IDs that were registered"""
    has_conflicts: bool
    r"""Whether one of the provided workflow specs has already been registered"""
    workflow_version_ids: List[str]
    r"""Deprecated: use workflow_registration_ids"""
    workflow_version_refs: List[WorkflowRegistrationRefResponseTypedDict]
    r"""Deprecated: use workflow_registration_refs"""
    workflow_registration_refs: NotRequired[
        List[WorkflowRegistrationRefResponseTypedDict]
    ]
    r"""List of workflow registration references"""
    warnings: NotRequired[List[str]]
    r"""Non-fatal warnings produced during registration"""


class WorkflowSpecsRegisterResponse(BaseModel):
    workflow_registration_ids: List[str]
    r"""List of workflow IDs that were registered"""

    has_conflicts: bool
    r"""Whether one of the provided workflow specs has already been registered"""

    workflow_version_ids: List[str]
    r"""Deprecated: use workflow_registration_ids"""

    workflow_version_refs: List[WorkflowRegistrationRefResponse]
    r"""Deprecated: use workflow_registration_refs"""

    workflow_registration_refs: Optional[List[WorkflowRegistrationRefResponse]] = None
    r"""List of workflow registration references"""

    warnings: Optional[List[str]] = None
    r"""Non-fatal warnings produced during registration"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["workflow_registration_refs", "warnings"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
