"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: e5247c5183bb

from __future__ import annotations
from .scheduledefinitionoutput import (
    ScheduleDefinitionOutput,
    ScheduleDefinitionOutputTypedDict,
)
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class WorkflowScheduleListResponseTypedDict(TypedDict):
    schedules: List[ScheduleDefinitionOutputTypedDict]
    r"""A list of workflow schedules"""
    next_page_token: NotRequired[Nullable[str]]
    r"""Token for the next page of results"""


class WorkflowScheduleListResponse(BaseModel):
    schedules: List[ScheduleDefinitionOutput]
    r"""A list of workflow schedules"""

    next_page_token: OptionalNullable[str] = UNSET
    r"""Token for the next page of results"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["next_page_token"]
        nullable_fields = ["next_page_token"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
