"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 43369570cb96

from __future__ import annotations
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class WorkflowTaskTimedOutAttributesTypedDict(TypedDict):
    r"""Attributes for workflow task timed out events."""

    task_id: str
    r"""Unique identifier for the task within the workflow execution."""
    timeout_type: NotRequired[Nullable[str]]
    r"""The type of timeout that occurred (e.g., 'START_TO_CLOSE', 'SCHEDULE_TO_START')."""


class WorkflowTaskTimedOutAttributes(BaseModel):
    r"""Attributes for workflow task timed out events."""

    task_id: str
    r"""Unique identifier for the task within the workflow execution."""

    timeout_type: OptionalNullable[str] = UNSET
    r"""The type of timeout that occurred (e.g., 'START_TO_CLOSE', 'SCHEDULE_TO_START')."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["timeout_type"]
        nullable_fields = ["timeout_type"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
