"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: b255b05e7395

from __future__ import annotations
from .workflowbasicdefinition import (
    WorkflowBasicDefinition,
    WorkflowBasicDefinitionTypedDict,
)
from mistralai.client.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class WorkflowListResponseTypedDict(TypedDict):
    workflows: List[WorkflowBasicDefinitionTypedDict]
    r"""A list of workflows"""
    next_cursor: Nullable[str]


class WorkflowListResponse(BaseModel):
    workflows: List[WorkflowBasicDefinition]
    r"""A list of workflows"""

    next_cursor: Nullable[str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = []
        nullable_fields = ["next_cursor"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
