[GLOBAL]
# That's where we define tools we want to use for our repo, here Python, and some linter/checker for the demo
backend_packages = [
    "pants.backend.python",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.experimental.python.lint.ruff.format",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.python.lint.docformatter",
]
pants_version = "2.21.0"

[source]
# Where Pants need to look at for our code
root_patterns = ["/src", "/tests", "/examples"]

[python]
interpreter_constraints = [">=3.9,<4.0"]

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>"]

[python-infer]
use_rust_parser = true

[test]
use_coverage = true

[python.resolves]
# Pants can create it's own .lock, here we use the existing one
poetry = "poetry.lock"
