"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from mistralai.gcp.client.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .apikeyauth import APIKeyAuth, APIKeyAuthTypedDict
    from .assistantmessage import (
        AssistantMessage,
        AssistantMessageContent,
        AssistantMessageContentTypedDict,
        AssistantMessageTypedDict,
    )
    from .builtinconnectors import BuiltInConnectors
    from .chatcompletionchoice import (
        ChatCompletionChoice,
        ChatCompletionChoiceFinishReason,
        ChatCompletionChoiceTypedDict,
    )
    from .chatcompletionrequest import (
        ChatCompletionRequest,
        ChatCompletionRequestMessage,
        ChatCompletionRequestMessageTypedDict,
        ChatCompletionRequestStop,
        ChatCompletionRequestStopTypedDict,
        ChatCompletionRequestTool,
        ChatCompletionRequestToolChoice,
        ChatCompletionRequestToolChoiceTypedDict,
        ChatCompletionRequestToolTypedDict,
        ChatCompletionRequestTypedDict,
    )
    from .chatcompletionresponse import (
        ChatCompletionResponse,
        ChatCompletionResponseTypedDict,
    )
    from .chatcompletionstreamrequest import (
        ChatCompletionStreamRequest,
        ChatCompletionStreamRequestMessage,
        ChatCompletionStreamRequestMessageTypedDict,
        ChatCompletionStreamRequestStop,
        ChatCompletionStreamRequestStopTypedDict,
        ChatCompletionStreamRequestTool,
        ChatCompletionStreamRequestToolChoice,
        ChatCompletionStreamRequestToolChoiceTypedDict,
        ChatCompletionStreamRequestToolTypedDict,
        ChatCompletionStreamRequestTypedDict,
    )
    from .codeinterpretertool import CodeInterpreterTool, CodeInterpreterToolTypedDict
    from .completionchunk import CompletionChunk, CompletionChunkTypedDict
    from .completionevent import CompletionEvent, CompletionEventTypedDict
    from .completionresponsestreamchoice import (
        CompletionResponseStreamChoice,
        CompletionResponseStreamChoiceFinishReason,
        CompletionResponseStreamChoiceTypedDict,
    )
    from .contentchunk import ContentChunk, ContentChunkTypedDict, UnknownContentChunk
    from .customconnector import (
        Authorization,
        AuthorizationTypedDict,
        CustomConnector,
        CustomConnectorTypedDict,
    )
    from .deltamessage import (
        DeltaMessage,
        DeltaMessageContent,
        DeltaMessageContentTypedDict,
        DeltaMessageTypedDict,
    )
    from .documentlibrarytool import DocumentLibraryTool, DocumentLibraryToolTypedDict
    from .fimcompletionrequest import (
        FIMCompletionRequest,
        FIMCompletionRequestStop,
        FIMCompletionRequestStopTypedDict,
        FIMCompletionRequestTypedDict,
    )
    from .fimcompletionresponse import (
        FIMCompletionResponse,
        FIMCompletionResponseTypedDict,
    )
    from .fimcompletionstreamrequest import (
        FIMCompletionStreamRequest,
        FIMCompletionStreamRequestStop,
        FIMCompletionStreamRequestStopTypedDict,
        FIMCompletionStreamRequestTypedDict,
    )
    from .function import Function, FunctionTypedDict
    from .functioncall import (
        Arguments,
        ArgumentsTypedDict,
        FunctionCall,
        FunctionCallTypedDict,
    )
    from .functionname import FunctionName, FunctionNameTypedDict
    from .guardrailconfig import GuardrailConfig, GuardrailConfigTypedDict
    from .imagedetail import ImageDetail
    from .imagegenerationtool import ImageGenerationTool, ImageGenerationToolTypedDict
    from .imageurl import ImageURL, ImageURLTypedDict
    from .imageurlchunk import (
        ImageURLChunk,
        ImageURLChunkTypedDict,
        ImageURLUnion,
        ImageURLUnionTypedDict,
    )
    from .jsonschema import JSONSchema, JSONSchemaTypedDict
    from .mistralpromptmode import MistralPromptMode
    from .moderationllmaction import ModerationLLMAction
    from .moderationllmv1categorythresholds import (
        ModerationLlmv1CategoryThresholds,
        ModerationLlmv1CategoryThresholdsTypedDict,
    )
    from .moderationllmv1config import (
        ModerationLlmv1Config,
        ModerationLlmv1ConfigTypedDict,
    )
    from .moderationllmv2categorythresholds import (
        ModerationLlmv2CategoryThresholds,
        ModerationLlmv2CategoryThresholdsTypedDict,
    )
    from .moderationllmv2config import (
        ModerationLlmv2Config,
        ModerationLlmv2ConfigTypedDict,
    )
    from .oauth2tokenauth import OAuth2TokenAuth, OAuth2TokenAuthTypedDict
    from .prediction import Prediction, PredictionTypedDict
    from .reasoningeffort import ReasoningEffort
    from .referencechunk import (
        ReferenceChunk,
        ReferenceChunkTypedDict,
        ReferenceID,
        ReferenceIDTypedDict,
    )
    from .responseformat import ResponseFormat, ResponseFormatTypedDict
    from .responseformats import ResponseFormats
    from .security import Security, SecurityTypedDict
    from .systemmessage import (
        SystemMessage,
        SystemMessageContent,
        SystemMessageContentTypedDict,
        SystemMessageTypedDict,
    )
    from .systemmessagecontentchunks import (
        SystemMessageContentChunks,
        SystemMessageContentChunksTypedDict,
    )
    from .textchunk import TextChunk, TextChunkTypedDict
    from .thinkchunk import ThinkChunk, ThinkChunkTypedDict, Thinking, ThinkingTypedDict
    from .tool import Tool, ToolTypedDict
    from .toolcall import ToolCall, ToolCallTypedDict
    from .toolchoice import ToolChoice, ToolChoiceTypedDict
    from .toolchoiceenum import ToolChoiceEnum
    from .toolconfiguration import ToolConfiguration, ToolConfigurationTypedDict
    from .toolmessage import (
        ToolMessage,
        ToolMessageContent,
        ToolMessageContentTypedDict,
        ToolMessageTypedDict,
    )
    from .toolreferencechunk import (
        ToolReferenceChunk,
        ToolReferenceChunkTool,
        ToolReferenceChunkToolTypedDict,
        ToolReferenceChunkTypedDict,
    )
    from .usageinfo import UsageInfo, UsageInfoTypedDict
    from .usermessage import (
        UserMessage,
        UserMessageContent,
        UserMessageContentTypedDict,
        UserMessageTypedDict,
    )
    from .validationerror import (
        Context,
        ContextTypedDict,
        Loc,
        LocTypedDict,
        ValidationError,
        ValidationErrorTypedDict,
    )
    from .websearchpremiumtool import (
        WebSearchPremiumTool,
        WebSearchPremiumToolTypedDict,
    )
    from .websearchtool import WebSearchTool, WebSearchToolTypedDict

__all__ = [
    "APIKeyAuth",
    "APIKeyAuthTypedDict",
    "Arguments",
    "ArgumentsTypedDict",
    "AssistantMessage",
    "AssistantMessageContent",
    "AssistantMessageContentTypedDict",
    "AssistantMessageTypedDict",
    "Authorization",
    "AuthorizationTypedDict",
    "BuiltInConnectors",
    "ChatCompletionChoice",
    "ChatCompletionChoiceFinishReason",
    "ChatCompletionChoiceTypedDict",
    "ChatCompletionRequest",
    "ChatCompletionRequestMessage",
    "ChatCompletionRequestMessageTypedDict",
    "ChatCompletionRequestStop",
    "ChatCompletionRequestStopTypedDict",
    "ChatCompletionRequestTool",
    "ChatCompletionRequestToolChoice",
    "ChatCompletionRequestToolChoiceTypedDict",
    "ChatCompletionRequestToolTypedDict",
    "ChatCompletionRequestTypedDict",
    "ChatCompletionResponse",
    "ChatCompletionResponseTypedDict",
    "ChatCompletionStreamRequest",
    "ChatCompletionStreamRequestMessage",
    "ChatCompletionStreamRequestMessageTypedDict",
    "ChatCompletionStreamRequestStop",
    "ChatCompletionStreamRequestStopTypedDict",
    "ChatCompletionStreamRequestTool",
    "ChatCompletionStreamRequestToolChoice",
    "ChatCompletionStreamRequestToolChoiceTypedDict",
    "ChatCompletionStreamRequestToolTypedDict",
    "ChatCompletionStreamRequestTypedDict",
    "CodeInterpreterTool",
    "CodeInterpreterToolTypedDict",
    "CompletionChunk",
    "CompletionChunkTypedDict",
    "CompletionEvent",
    "CompletionEventTypedDict",
    "CompletionResponseStreamChoice",
    "CompletionResponseStreamChoiceFinishReason",
    "CompletionResponseStreamChoiceTypedDict",
    "ContentChunk",
    "ContentChunkTypedDict",
    "Context",
    "ContextTypedDict",
    "CustomConnector",
    "CustomConnectorTypedDict",
    "DeltaMessage",
    "DeltaMessageContent",
    "DeltaMessageContentTypedDict",
    "DeltaMessageTypedDict",
    "DocumentLibraryTool",
    "DocumentLibraryToolTypedDict",
    "FIMCompletionRequest",
    "FIMCompletionRequestStop",
    "FIMCompletionRequestStopTypedDict",
    "FIMCompletionRequestTypedDict",
    "FIMCompletionResponse",
    "FIMCompletionResponseTypedDict",
    "FIMCompletionStreamRequest",
    "FIMCompletionStreamRequestStop",
    "FIMCompletionStreamRequestStopTypedDict",
    "FIMCompletionStreamRequestTypedDict",
    "Function",
    "FunctionCall",
    "FunctionCallTypedDict",
    "FunctionName",
    "FunctionNameTypedDict",
    "FunctionTypedDict",
    "GuardrailConfig",
    "GuardrailConfigTypedDict",
    "ImageDetail",
    "ImageGenerationTool",
    "ImageGenerationToolTypedDict",
    "ImageURL",
    "ImageURLChunk",
    "ImageURLChunkTypedDict",
    "ImageURLTypedDict",
    "ImageURLUnion",
    "ImageURLUnionTypedDict",
    "JSONSchema",
    "JSONSchemaTypedDict",
    "Loc",
    "LocTypedDict",
    "MistralPromptMode",
    "ModerationLLMAction",
    "ModerationLlmv1CategoryThresholds",
    "ModerationLlmv1CategoryThresholdsTypedDict",
    "ModerationLlmv1Config",
    "ModerationLlmv1ConfigTypedDict",
    "ModerationLlmv2CategoryThresholds",
    "ModerationLlmv2CategoryThresholdsTypedDict",
    "ModerationLlmv2Config",
    "ModerationLlmv2ConfigTypedDict",
    "OAuth2TokenAuth",
    "OAuth2TokenAuthTypedDict",
    "Prediction",
    "PredictionTypedDict",
    "ReasoningEffort",
    "ReferenceChunk",
    "ReferenceChunkTypedDict",
    "ReferenceID",
    "ReferenceIDTypedDict",
    "ResponseFormat",
    "ResponseFormatTypedDict",
    "ResponseFormats",
    "Security",
    "SecurityTypedDict",
    "SystemMessage",
    "SystemMessageContent",
    "SystemMessageContentChunks",
    "SystemMessageContentChunksTypedDict",
    "SystemMessageContentTypedDict",
    "SystemMessageTypedDict",
    "TextChunk",
    "TextChunkTypedDict",
    "ThinkChunk",
    "ThinkChunkTypedDict",
    "Thinking",
    "ThinkingTypedDict",
    "Tool",
    "ToolCall",
    "ToolCallTypedDict",
    "ToolChoice",
    "ToolChoiceEnum",
    "ToolChoiceTypedDict",
    "ToolConfiguration",
    "ToolConfigurationTypedDict",
    "ToolMessage",
    "ToolMessageContent",
    "ToolMessageContentTypedDict",
    "ToolMessageTypedDict",
    "ToolReferenceChunk",
    "ToolReferenceChunkTool",
    "ToolReferenceChunkToolTypedDict",
    "ToolReferenceChunkTypedDict",
    "ToolTypedDict",
    "UnknownContentChunk",
    "UsageInfo",
    "UsageInfoTypedDict",
    "UserMessage",
    "UserMessageContent",
    "UserMessageContentTypedDict",
    "UserMessageTypedDict",
    "ValidationError",
    "ValidationErrorTypedDict",
    "WebSearchPremiumTool",
    "WebSearchPremiumToolTypedDict",
    "WebSearchTool",
    "WebSearchToolTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "APIKeyAuth": ".apikeyauth",
    "APIKeyAuthTypedDict": ".apikeyauth",
    "AssistantMessage": ".assistantmessage",
    "AssistantMessageContent": ".assistantmessage",
    "AssistantMessageContentTypedDict": ".assistantmessage",
    "AssistantMessageTypedDict": ".assistantmessage",
    "BuiltInConnectors": ".builtinconnectors",
    "ChatCompletionChoice": ".chatcompletionchoice",
    "ChatCompletionChoiceFinishReason": ".chatcompletionchoice",
    "ChatCompletionChoiceTypedDict": ".chatcompletionchoice",
    "ChatCompletionRequest": ".chatcompletionrequest",
    "ChatCompletionRequestMessage": ".chatcompletionrequest",
    "ChatCompletionRequestMessageTypedDict": ".chatcompletionrequest",
    "ChatCompletionRequestStop": ".chatcompletionrequest",
    "ChatCompletionRequestStopTypedDict": ".chatcompletionrequest",
    "ChatCompletionRequestTool": ".chatcompletionrequest",
    "ChatCompletionRequestToolChoice": ".chatcompletionrequest",
    "ChatCompletionRequestToolChoiceTypedDict": ".chatcompletionrequest",
    "ChatCompletionRequestToolTypedDict": ".chatcompletionrequest",
    "ChatCompletionRequestTypedDict": ".chatcompletionrequest",
    "ChatCompletionResponse": ".chatcompletionresponse",
    "ChatCompletionResponseTypedDict": ".chatcompletionresponse",
    "ChatCompletionStreamRequest": ".chatcompletionstreamrequest",
    "ChatCompletionStreamRequestMessage": ".chatcompletionstreamrequest",
    "ChatCompletionStreamRequestMessageTypedDict": ".chatcompletionstreamrequest",
    "ChatCompletionStreamRequestStop": ".chatcompletionstreamrequest",
    "ChatCompletionStreamRequestStopTypedDict": ".chatcompletionstreamrequest",
    "ChatCompletionStreamRequestTool": ".chatcompletionstreamrequest",
    "ChatCompletionStreamRequestToolChoice": ".chatcompletionstreamrequest",
    "ChatCompletionStreamRequestToolChoiceTypedDict": ".chatcompletionstreamrequest",
    "ChatCompletionStreamRequestToolTypedDict": ".chatcompletionstreamrequest",
    "ChatCompletionStreamRequestTypedDict": ".chatcompletionstreamrequest",
    "CodeInterpreterTool": ".codeinterpretertool",
    "CodeInterpreterToolTypedDict": ".codeinterpretertool",
    "CompletionChunk": ".completionchunk",
    "CompletionChunkTypedDict": ".completionchunk",
    "CompletionEvent": ".completionevent",
    "CompletionEventTypedDict": ".completionevent",
    "CompletionResponseStreamChoice": ".completionresponsestreamchoice",
    "CompletionResponseStreamChoiceFinishReason": ".completionresponsestreamchoice",
    "CompletionResponseStreamChoiceTypedDict": ".completionresponsestreamchoice",
    "ContentChunk": ".contentchunk",
    "ContentChunkTypedDict": ".contentchunk",
    "UnknownContentChunk": ".contentchunk",
    "Authorization": ".customconnector",
    "AuthorizationTypedDict": ".customconnector",
    "CustomConnector": ".customconnector",
    "CustomConnectorTypedDict": ".customconnector",
    "DeltaMessage": ".deltamessage",
    "DeltaMessageContent": ".deltamessage",
    "DeltaMessageContentTypedDict": ".deltamessage",
    "DeltaMessageTypedDict": ".deltamessage",
    "DocumentLibraryTool": ".documentlibrarytool",
    "DocumentLibraryToolTypedDict": ".documentlibrarytool",
    "FIMCompletionRequest": ".fimcompletionrequest",
    "FIMCompletionRequestStop": ".fimcompletionrequest",
    "FIMCompletionRequestStopTypedDict": ".fimcompletionrequest",
    "FIMCompletionRequestTypedDict": ".fimcompletionrequest",
    "FIMCompletionResponse": ".fimcompletionresponse",
    "FIMCompletionResponseTypedDict": ".fimcompletionresponse",
    "FIMCompletionStreamRequest": ".fimcompletionstreamrequest",
    "FIMCompletionStreamRequestStop": ".fimcompletionstreamrequest",
    "FIMCompletionStreamRequestStopTypedDict": ".fimcompletionstreamrequest",
    "FIMCompletionStreamRequestTypedDict": ".fimcompletionstreamrequest",
    "Function": ".function",
    "FunctionTypedDict": ".function",
    "Arguments": ".functioncall",
    "ArgumentsTypedDict": ".functioncall",
    "FunctionCall": ".functioncall",
    "FunctionCallTypedDict": ".functioncall",
    "FunctionName": ".functionname",
    "FunctionNameTypedDict": ".functionname",
    "GuardrailConfig": ".guardrailconfig",
    "GuardrailConfigTypedDict": ".guardrailconfig",
    "ImageDetail": ".imagedetail",
    "ImageGenerationTool": ".imagegenerationtool",
    "ImageGenerationToolTypedDict": ".imagegenerationtool",
    "ImageURL": ".imageurl",
    "ImageURLTypedDict": ".imageurl",
    "ImageURLChunk": ".imageurlchunk",
    "ImageURLChunkTypedDict": ".imageurlchunk",
    "ImageURLUnion": ".imageurlchunk",
    "ImageURLUnionTypedDict": ".imageurlchunk",
    "JSONSchema": ".jsonschema",
    "JSONSchemaTypedDict": ".jsonschema",
    "MistralPromptMode": ".mistralpromptmode",
    "ModerationLLMAction": ".moderationllmaction",
    "ModerationLlmv1CategoryThresholds": ".moderationllmv1categorythresholds",
    "ModerationLlmv1CategoryThresholdsTypedDict": ".moderationllmv1categorythresholds",
    "ModerationLlmv1Config": ".moderationllmv1config",
    "ModerationLlmv1ConfigTypedDict": ".moderationllmv1config",
    "ModerationLlmv2CategoryThresholds": ".moderationllmv2categorythresholds",
    "ModerationLlmv2CategoryThresholdsTypedDict": ".moderationllmv2categorythresholds",
    "ModerationLlmv2Config": ".moderationllmv2config",
    "ModerationLlmv2ConfigTypedDict": ".moderationllmv2config",
    "OAuth2TokenAuth": ".oauth2tokenauth",
    "OAuth2TokenAuthTypedDict": ".oauth2tokenauth",
    "Prediction": ".prediction",
    "PredictionTypedDict": ".prediction",
    "ReasoningEffort": ".reasoningeffort",
    "ReferenceChunk": ".referencechunk",
    "ReferenceChunkTypedDict": ".referencechunk",
    "ReferenceID": ".referencechunk",
    "ReferenceIDTypedDict": ".referencechunk",
    "ResponseFormat": ".responseformat",
    "ResponseFormatTypedDict": ".responseformat",
    "ResponseFormats": ".responseformats",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "SystemMessage": ".systemmessage",
    "SystemMessageContent": ".systemmessage",
    "SystemMessageContentTypedDict": ".systemmessage",
    "SystemMessageTypedDict": ".systemmessage",
    "SystemMessageContentChunks": ".systemmessagecontentchunks",
    "SystemMessageContentChunksTypedDict": ".systemmessagecontentchunks",
    "TextChunk": ".textchunk",
    "TextChunkTypedDict": ".textchunk",
    "ThinkChunk": ".thinkchunk",
    "ThinkChunkTypedDict": ".thinkchunk",
    "Thinking": ".thinkchunk",
    "ThinkingTypedDict": ".thinkchunk",
    "Tool": ".tool",
    "ToolTypedDict": ".tool",
    "ToolCall": ".toolcall",
    "ToolCallTypedDict": ".toolcall",
    "ToolChoice": ".toolchoice",
    "ToolChoiceTypedDict": ".toolchoice",
    "ToolChoiceEnum": ".toolchoiceenum",
    "ToolConfiguration": ".toolconfiguration",
    "ToolConfigurationTypedDict": ".toolconfiguration",
    "ToolMessage": ".toolmessage",
    "ToolMessageContent": ".toolmessage",
    "ToolMessageContentTypedDict": ".toolmessage",
    "ToolMessageTypedDict": ".toolmessage",
    "ToolReferenceChunk": ".toolreferencechunk",
    "ToolReferenceChunkTool": ".toolreferencechunk",
    "ToolReferenceChunkToolTypedDict": ".toolreferencechunk",
    "ToolReferenceChunkTypedDict": ".toolreferencechunk",
    "UsageInfo": ".usageinfo",
    "UsageInfoTypedDict": ".usageinfo",
    "UserMessage": ".usermessage",
    "UserMessageContent": ".usermessage",
    "UserMessageContentTypedDict": ".usermessage",
    "UserMessageTypedDict": ".usermessage",
    "Context": ".validationerror",
    "ContextTypedDict": ".validationerror",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
    "WebSearchPremiumTool": ".websearchpremiumtool",
    "WebSearchPremiumToolTypedDict": ".websearchpremiumtool",
    "WebSearchTool": ".websearchtool",
    "WebSearchToolTypedDict": ".websearchtool",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
