// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPostV1Embeddings(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "embeddings_v1_embeddings_post[0]":
			dir.HandlerFunc("embeddings_v1_embeddings_post", testEmbeddingsV1EmbeddingsPostEmbeddingsV1EmbeddingsPost0)(w, req)
		case "embeddings_v1_embeddings_post-userExample[0]":
			dir.HandlerFunc("embeddings_v1_embeddings_post", testEmbeddingsV1EmbeddingsPostEmbeddingsV1EmbeddingsPostUserExample0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testEmbeddingsV1EmbeddingsPostEmbeddingsV1EmbeddingsPost0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, "Bearer"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.EmbeddingResponse = &components.EmbeddingResponse{
		ID:     "cmpl-e5cc70bb28c444948073e77776eb30ef",
		Object: "chat.completion",
		Model:  "mistral-small-latest",
		Usage: components.UsageInfo{
			PromptTokens:     types.Int64(0),
			CompletionTokens: types.Int64(0),
			TotalTokens:      types.Int64(0),
		},
		Data: []components.EmbeddingResponseData{
			components.EmbeddingResponseData{
				Object: types.String("embedding"),
				Embedding: []float64{
					0.1,
					0.2,
					0.3,
				},
				Index: types.Int64(0),
			},
			components.EmbeddingResponseData{
				Object: types.String("embedding"),
				Embedding: []float64{
					0.4,
					0.5,
					0.6,
				},
				Index: types.Int64(1),
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testEmbeddingsV1EmbeddingsPostEmbeddingsV1EmbeddingsPostUserExample0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, "Bearer"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.EmbeddingResponse = &components.EmbeddingResponse{
		ID:     "cmpl-e5cc70bb28c444948073e77776eb30ef",
		Object: "list",
		Model:  "mistral-embed",
		Usage: components.UsageInfo{
			PromptTokens:       types.Int64(15),
			CompletionTokens:   types.Int64(0),
			TotalTokens:        types.Int64(15),
			PromptAudioSeconds: nil,
		},
		Data: []components.EmbeddingResponseData{
			components.EmbeddingResponseData{
				Object: types.String("embedding"),
				Embedding: []float64{
					-0.016632080078125,
					0.0701904296875,
					0.03143310546875,
					0.01309967041015625,
					0.0202789306640625,
				},
				Index: types.Int64(0),
			},
			components.EmbeddingResponseData{
				Object: types.String("embedding"),
				Embedding: []float64{
					-0.0230560302734375,
					0.039337158203125,
					0.0521240234375,
					-0.0184783935546875,
					0.034271240234375,
				},
				Index: types.Int64(1),
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
