"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from mistralai.client import Mistral, models
import os
from tests.test_client import create_test_http_client


def test_classifiers_moderations_v1_moderations_post():
    test_http_client = create_test_http_client("moderations_v1_moderations_post")

    with Mistral(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("MISTRAL_API_KEY", "value"),
    ) as mistral:
        assert mistral is not None

        res = mistral.classifiers.moderate(
            model="Durango",
            inputs=[
                "<value 1>",
                "<value 2>",
            ],
        )
        assert res is not None
        assert res == models.ModerationResponse(
            id="mod-e5cc70bb28c444948073e77776eb30ef",
            model="Corvette",
            results=[
                models.ModerationObject(),
            ],
        )


def test_classifiers_moderations_v1_moderations_post_user_example():
    test_http_client = create_test_http_client(
        "moderations_v1_moderations_post-userExample"
    )

    with Mistral(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("MISTRAL_API_KEY", "value"),
    ) as mistral:
        assert mistral is not None

        res = mistral.classifiers.moderate(
            model="mistral-moderation-latest", inputs="<value>"
        )
        assert res is not None
        assert res == models.ModerationResponse(
            id="4d71ae510af942108ef7344f903e2b88",
            model="mistral-moderation-latest",
            results=[
                models.ModerationObject(
                    categories={
                        "sexual": False,
                        "hate_and_discrimination": False,
                        "violence_and_threats": False,
                        "dangerous_and_criminal_content": False,
                        "selfharm": False,
                        "health": False,
                        "financial": False,
                        "law": False,
                        "pii": False,
                    },
                    category_scores={
                        "sexual": 0.0011335690505802631,
                        "hate_and_discrimination": 0.0030753696337342262,
                        "violence_and_threats": 0.0003569706459529698,
                        "dangerous_and_criminal_content": 0.002251847181469202,
                        "selfharm": 0.00017952796770259738,
                        "health": 0.0002780309587251395,
                        "financial": 0.00008481103577651083,
                        "law": 0.00004539786823443137,
                        "pii": 0.0023967307060956955,
                    },
                ),
                models.ModerationObject(
                    categories={
                        "sexual": False,
                        "hate_and_discrimination": False,
                        "violence_and_threats": False,
                        "dangerous_and_criminal_content": False,
                        "selfharm": False,
                        "health": False,
                        "financial": False,
                        "law": False,
                        "pii": False,
                    },
                    category_scores={
                        "sexual": 0.000626334105618298,
                        "hate_and_discrimination": 0.0013670255430042744,
                        "violence_and_threats": 0.0002611903182696551,
                        "dangerous_and_criminal_content": 0.0030753696337342262,
                        "selfharm": 0.00010889690747717395,
                        "health": 0.00015843621804378927,
                        "financial": 0.000191104321856983,
                        "law": 0.00004006369272246957,
                        "pii": 0.0035936026833951473,
                    },
                ),
            ],
        )


def test_classifiers_chat_moderations_v1_chat_moderations_post():
    test_http_client = create_test_http_client(
        "chat_moderations_v1_chat_moderations_post"
    )

    with Mistral(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("MISTRAL_API_KEY", "value"),
    ) as mistral:
        assert mistral is not None

        res = mistral.classifiers.moderate_chat(
            inputs=[
                {
                    "role": "tool",
                    "content": "<value>",
                },
            ],
            model="LeBaron",
        )
        assert res is not None
        assert res == models.ModerationResponse(
            id="mod-e5cc70bb28c444948073e77776eb30ef",
            model="Explorer",
            results=[
                models.ModerationObject(),
            ],
        )


def test_classifiers_chat_moderations_v1_chat_moderations_post_user_example():
    test_http_client = create_test_http_client(
        "chat_moderations_v1_chat_moderations_post-userExample"
    )

    with Mistral(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("MISTRAL_API_KEY", "value"),
    ) as mistral:
        assert mistral is not None

        res = mistral.classifiers.moderate_chat(
            inputs=[
                {
                    "role": "tool",
                    "content": "<value>",
                },
            ],
            model="LeBaron",
        )
        assert res is not None
        assert res == models.ModerationResponse(
            id="352bce1a55814127a3b0bc4fb8f02a35",
            model="mistral-moderation-latest",
            results=[
                models.ModerationObject(
                    categories={
                        "sexual": False,
                        "hate_and_discrimination": False,
                        "violence_and_threats": False,
                        "dangerous_and_criminal_content": False,
                        "selfharm": False,
                        "health": False,
                        "financial": False,
                        "law": False,
                        "pii": False,
                    },
                    category_scores={
                        "sexual": 0.0010322310263291001,
                        "hate_and_discrimination": 0.001597845577634871,
                        "violence_and_threats": 0.00020342698553577065,
                        "dangerous_and_criminal_content": 0.0029810327105224133,
                        "selfharm": 0.00017952796770259738,
                        "health": 0.0002959570847451687,
                        "financial": 0.000079673009167891,
                        "law": 0.00004539786823443137,
                        "pii": 0.004198795650154352,
                    },
                ),
            ],
        )


def test_classifiers_classifications_v1_classifications_post():
    test_http_client = create_test_http_client(
        "classifications_v1_classifications_post"
    )

    with Mistral(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("MISTRAL_API_KEY", "value"),
    ) as mistral:
        assert mistral is not None

        res = mistral.classifiers.classify(
            model="mistral-moderation-latest",
            inputs=[
                "<value 1>",
            ],
        )
        assert res is not None
        assert res == models.ClassificationResponse(
            id="mod-e5cc70bb28c444948073e77776eb30ef",
            model="ATS",
            results=[
                {},
                {
                    "key": models.ClassificationTargetResult(
                        scores={
                            "key": 2080.19,
                        },
                    ),
                },
            ],
        )


def test_classifiers_chat_classifications_v1_chat_classifications_post():
    test_http_client = create_test_http_client(
        "chat_classifications_v1_chat_classifications_post"
    )

    with Mistral(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("MISTRAL_API_KEY", "value"),
    ) as mistral:
        assert mistral is not None

        res = mistral.classifiers.classify_chat(
            model="Camry",
            input=[
                {
                    "messages": [
                        {
                            "role": "system",
                            "content": "<value>",
                        },
                    ],
                },
            ],
        )
        assert res is not None
        assert res == models.ClassificationResponse(
            id="mod-e5cc70bb28c444948073e77776eb30ef",
            model="Altima",
            results=[
                {},
                {
                    "key": models.ClassificationTargetResult(
                        scores={
                            "key": 1360.53,
                            "key1": 5946.42,
                        },
                    ),
                },
                {
                    "key": models.ClassificationTargetResult(
                        scores={
                            "key": 1360.53,
                            "key1": 5946.42,
                        },
                    ),
                },
            ],
        )
