"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from mistralai.client import Mistral, models
import os
from tests.test_client import create_test_http_client


def test_accesses_libraries_share_list_v1():
    test_http_client = create_test_http_client("libraries_share_list_v1")

    with Mistral(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("MISTRAL_API_KEY", "value"),
    ) as mistral:
        assert mistral is not None

        res = mistral.beta.libraries.accesses.list(
            library_id="d2169833-d8e2-416e-a372-76518d3d99c2"
        )
        assert res is not None
        assert res == models.ListSharingOut(
            data=[
                models.SharingOut(
                    library_id="26c08a7a-d226-4d29-b4d8-c08f0ad41dd1",
                    org_id="254e3633-51b9-47a9-bc14-466ecf29d167",
                    role="<value>",
                    share_with_type="<value>",
                    share_with_uuid="815eb88e-1f97-4782-863f-5fd00d37268b",
                ),
            ],
        )


def test_accesses_libraries_share_create_v1():
    test_http_client = create_test_http_client("libraries_share_create_v1")

    with Mistral(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("MISTRAL_API_KEY", "value"),
    ) as mistral:
        assert mistral is not None

        res = mistral.beta.libraries.accesses.update_or_create(
            library_id="36de3a24-5b1c-4c8f-9d84-d5642205a976",
            level="Viewer",
            share_with_uuid="0ae92ecb-21ed-47c5-9f7e-0b2cbe325a20",
            share_with_type="User",
        )
        assert res is not None
        assert res == models.SharingOut(
            library_id="45b3a5b2-8b81-4453-9130-ded7f1e5a366",
            org_id="0fa6e542-f04b-431e-a1be-76a9a92b0e68",
            role="<value>",
            share_with_type="<value>",
            share_with_uuid="cdbcc0c5-e577-4880-8ed3-f919421d4fc5",
        )


def test_accesses_libraries_share_delete_v1():
    test_http_client = create_test_http_client("libraries_share_delete_v1")

    with Mistral(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key=os.getenv("MISTRAL_API_KEY", "value"),
    ) as mistral:
        assert mistral is not None

        res = mistral.beta.libraries.accesses.delete(
            library_id="709e3cad-9fb2-4f4e-bf88-143cf1808107",
            share_with_uuid="b843cc47-ce8f-4354-8cfc-5fcd7fb2865b",
            share_with_type="User",
        )
        assert res is not None
        assert res == models.SharingOut(
            library_id="7f9c6af4-e362-4cf1-9363-0409d51c2dfa",
            org_id="6b2cac3a-b29c-4d8f-bebb-0db06ec1bf97",
            role="<value>",
            share_with_type="<value>",
            share_with_uuid="618c78f1-41ca-45c3-8ef2-7d78898c7061",
        )
