python_sources(
    name="lib"
)

resource(
    name="py_typed",
    source="py.typed",
)

# If we want we can use Pants to handle the build of our app too

# python_distribution(
#     name="mistralai",
#     dependencies=[
#         ":lib",
#     ],
#     wheel=True,
#     sdist=True,
#     provides=setup_py(
#         name="mistralai",
#         version="0.4.2",
#         authors = ["Bam4d <bam4d@mistral.ai>"],
#         license="Apache 2.0 License",
#         description="",
#         readme = "README.md",
#     ),
# )