// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
)

type AudioTranscriptionRequest struct {
	// ID of the model to be used.
	Model string `multipartForm:"name=model"`
	File  *File  `multipartForm:"file,name=file"`
	// Url of a file to be transcribed
	FileURL *string `multipartForm:"name=file_url"`
	// ID of a file uploaded to /v1/files
	FileID *string `multipartForm:"name=file_id"`
	// Language of the audio, e.g. 'en'. Providing the language can boost accuracy.
	Language    *string  `multipartForm:"name=language"`
	Temperature *float64 `multipartForm:"name=temperature"`
	stream      *bool    `const:"false" multipartForm:"name=stream"`
	Diarize     *bool    `default:"false" multipartForm:"name=diarize"`
	ContextBias []string `multipartForm:"name=context_bias"`
	// Granularities of timestamps to include in the response.
	TimestampGranularities []TimestampGranularity `multipartForm:"name=timestamp_granularities"`
}

func (a AudioTranscriptionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AudioTranscriptionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"model"}); err != nil {
		return err
	}
	return nil
}

func (o *AudioTranscriptionRequest) GetModel() string {
	if o == nil {
		return ""
	}
	return o.Model
}

func (o *AudioTranscriptionRequest) GetFile() *File {
	if o == nil {
		return nil
	}
	return o.File
}

func (o *AudioTranscriptionRequest) GetFileURL() *string {
	if o == nil {
		return nil
	}
	return o.FileURL
}

func (o *AudioTranscriptionRequest) GetFileID() *string {
	if o == nil {
		return nil
	}
	return o.FileID
}

func (o *AudioTranscriptionRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *AudioTranscriptionRequest) GetTemperature() *float64 {
	if o == nil {
		return nil
	}
	return o.Temperature
}

func (o *AudioTranscriptionRequest) GetStream() *bool {
	return types.Bool(false)
}

func (o *AudioTranscriptionRequest) GetDiarize() *bool {
	if o == nil {
		return nil
	}
	return o.Diarize
}

func (o *AudioTranscriptionRequest) GetContextBias() []string {
	if o == nil {
		return nil
	}
	return o.ContextBias
}

func (o *AudioTranscriptionRequest) GetTimestampGranularities() []TimestampGranularity {
	if o == nil {
		return nil
	}
	return o.TimestampGranularities
}
