// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type BuiltInConnectors string

const (
	BuiltInConnectorsWebSearch        BuiltInConnectors = "web_search"
	BuiltInConnectorsWebSearchPremium BuiltInConnectors = "web_search_premium"
	BuiltInConnectorsCodeInterpreter  BuiltInConnectors = "code_interpreter"
	BuiltInConnectorsImageGeneration  BuiltInConnectors = "image_generation"
	BuiltInConnectorsDocumentLibrary  BuiltInConnectors = "document_library"
)

func (e BuiltInConnectors) ToPointer() *BuiltInConnectors {
	return &e
}
func (e *BuiltInConnectors) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "web_search":
		fallthrough
	case "web_search_premium":
		fallthrough
	case "code_interpreter":
		fallthrough
	case "image_generation":
		fallthrough
	case "document_library":
		*e = BuiltInConnectors(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BuiltInConnectors: %v", v)
	}
}
