// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/utils"
)

type ChatModerationRequestInputs2Type string

const (
	ChatModerationRequestInputs2TypeAssistant ChatModerationRequestInputs2Type = "assistant"
	ChatModerationRequestInputs2TypeSystem    ChatModerationRequestInputs2Type = "system"
	ChatModerationRequestInputs2TypeTool      ChatModerationRequestInputs2Type = "tool"
	ChatModerationRequestInputs2TypeUser      ChatModerationRequestInputs2Type = "user"
)

type ChatModerationRequestInputs2 struct {
	SystemMessage    *SystemMessage    `queryParam:"inline"`
	UserMessage      *UserMessage      `queryParam:"inline"`
	AssistantMessage *AssistantMessage `queryParam:"inline"`
	ToolMessage      *ToolMessage      `queryParam:"inline"`

	Type ChatModerationRequestInputs2Type
}

func CreateChatModerationRequestInputs2Assistant(assistant AssistantMessage) ChatModerationRequestInputs2 {
	typ := ChatModerationRequestInputs2TypeAssistant

	return ChatModerationRequestInputs2{
		AssistantMessage: &assistant,
		Type:             typ,
	}
}

func CreateChatModerationRequestInputs2System(system SystemMessage) ChatModerationRequestInputs2 {
	typ := ChatModerationRequestInputs2TypeSystem

	return ChatModerationRequestInputs2{
		SystemMessage: &system,
		Type:          typ,
	}
}

func CreateChatModerationRequestInputs2Tool(tool ToolMessage) ChatModerationRequestInputs2 {
	typ := ChatModerationRequestInputs2TypeTool

	return ChatModerationRequestInputs2{
		ToolMessage: &tool,
		Type:        typ,
	}
}

func CreateChatModerationRequestInputs2User(user UserMessage) ChatModerationRequestInputs2 {
	typ := ChatModerationRequestInputs2TypeUser

	return ChatModerationRequestInputs2{
		UserMessage: &user,
		Type:        typ,
	}
}

func (u *ChatModerationRequestInputs2) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Role string `json:"role"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Role {
	case "assistant":
		assistantMessage := new(AssistantMessage)
		if err := utils.UnmarshalJSON(data, &assistantMessage, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Role == assistant) type AssistantMessage within ChatModerationRequestInputs2: %w", string(data), err)
		}

		u.AssistantMessage = assistantMessage
		u.Type = ChatModerationRequestInputs2TypeAssistant
		return nil
	case "system":
		systemMessage := new(SystemMessage)
		if err := utils.UnmarshalJSON(data, &systemMessage, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Role == system) type SystemMessage within ChatModerationRequestInputs2: %w", string(data), err)
		}

		u.SystemMessage = systemMessage
		u.Type = ChatModerationRequestInputs2TypeSystem
		return nil
	case "tool":
		toolMessage := new(ToolMessage)
		if err := utils.UnmarshalJSON(data, &toolMessage, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Role == tool) type ToolMessage within ChatModerationRequestInputs2: %w", string(data), err)
		}

		u.ToolMessage = toolMessage
		u.Type = ChatModerationRequestInputs2TypeTool
		return nil
	case "user":
		userMessage := new(UserMessage)
		if err := utils.UnmarshalJSON(data, &userMessage, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Role == user) type UserMessage within ChatModerationRequestInputs2: %w", string(data), err)
		}

		u.UserMessage = userMessage
		u.Type = ChatModerationRequestInputs2TypeUser
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatModerationRequestInputs2", string(data))
}

func (u ChatModerationRequestInputs2) MarshalJSON() ([]byte, error) {
	if u.SystemMessage != nil {
		return utils.MarshalJSON(u.SystemMessage, "", true)
	}

	if u.UserMessage != nil {
		return utils.MarshalJSON(u.UserMessage, "", true)
	}

	if u.AssistantMessage != nil {
		return utils.MarshalJSON(u.AssistantMessage, "", true)
	}

	if u.ToolMessage != nil {
		return utils.MarshalJSON(u.ToolMessage, "", true)
	}

	return nil, errors.New("could not marshal union type ChatModerationRequestInputs2: all fields are null")
}

type ChatModerationRequestInputs1Type string

const (
	ChatModerationRequestInputs1TypeAssistant ChatModerationRequestInputs1Type = "assistant"
	ChatModerationRequestInputs1TypeSystem    ChatModerationRequestInputs1Type = "system"
	ChatModerationRequestInputs1TypeTool      ChatModerationRequestInputs1Type = "tool"
	ChatModerationRequestInputs1TypeUser      ChatModerationRequestInputs1Type = "user"
)

type ChatModerationRequestInputs1 struct {
	SystemMessage    *SystemMessage    `queryParam:"inline"`
	UserMessage      *UserMessage      `queryParam:"inline"`
	AssistantMessage *AssistantMessage `queryParam:"inline"`
	ToolMessage      *ToolMessage      `queryParam:"inline"`

	Type ChatModerationRequestInputs1Type
}

func CreateChatModerationRequestInputs1Assistant(assistant AssistantMessage) ChatModerationRequestInputs1 {
	typ := ChatModerationRequestInputs1TypeAssistant

	return ChatModerationRequestInputs1{
		AssistantMessage: &assistant,
		Type:             typ,
	}
}

func CreateChatModerationRequestInputs1System(system SystemMessage) ChatModerationRequestInputs1 {
	typ := ChatModerationRequestInputs1TypeSystem

	return ChatModerationRequestInputs1{
		SystemMessage: &system,
		Type:          typ,
	}
}

func CreateChatModerationRequestInputs1Tool(tool ToolMessage) ChatModerationRequestInputs1 {
	typ := ChatModerationRequestInputs1TypeTool

	return ChatModerationRequestInputs1{
		ToolMessage: &tool,
		Type:        typ,
	}
}

func CreateChatModerationRequestInputs1User(user UserMessage) ChatModerationRequestInputs1 {
	typ := ChatModerationRequestInputs1TypeUser

	return ChatModerationRequestInputs1{
		UserMessage: &user,
		Type:        typ,
	}
}

func (u *ChatModerationRequestInputs1) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Role string `json:"role"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Role {
	case "assistant":
		assistantMessage := new(AssistantMessage)
		if err := utils.UnmarshalJSON(data, &assistantMessage, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Role == assistant) type AssistantMessage within ChatModerationRequestInputs1: %w", string(data), err)
		}

		u.AssistantMessage = assistantMessage
		u.Type = ChatModerationRequestInputs1TypeAssistant
		return nil
	case "system":
		systemMessage := new(SystemMessage)
		if err := utils.UnmarshalJSON(data, &systemMessage, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Role == system) type SystemMessage within ChatModerationRequestInputs1: %w", string(data), err)
		}

		u.SystemMessage = systemMessage
		u.Type = ChatModerationRequestInputs1TypeSystem
		return nil
	case "tool":
		toolMessage := new(ToolMessage)
		if err := utils.UnmarshalJSON(data, &toolMessage, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Role == tool) type ToolMessage within ChatModerationRequestInputs1: %w", string(data), err)
		}

		u.ToolMessage = toolMessage
		u.Type = ChatModerationRequestInputs1TypeTool
		return nil
	case "user":
		userMessage := new(UserMessage)
		if err := utils.UnmarshalJSON(data, &userMessage, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Role == user) type UserMessage within ChatModerationRequestInputs1: %w", string(data), err)
		}

		u.UserMessage = userMessage
		u.Type = ChatModerationRequestInputs1TypeUser
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatModerationRequestInputs1", string(data))
}

func (u ChatModerationRequestInputs1) MarshalJSON() ([]byte, error) {
	if u.SystemMessage != nil {
		return utils.MarshalJSON(u.SystemMessage, "", true)
	}

	if u.UserMessage != nil {
		return utils.MarshalJSON(u.UserMessage, "", true)
	}

	if u.AssistantMessage != nil {
		return utils.MarshalJSON(u.AssistantMessage, "", true)
	}

	if u.ToolMessage != nil {
		return utils.MarshalJSON(u.ToolMessage, "", true)
	}

	return nil, errors.New("could not marshal union type ChatModerationRequestInputs1: all fields are null")
}

type ChatModerationRequestInputs3Type string

const (
	ChatModerationRequestInputs3TypeArrayOfChatModerationRequestInputs1        ChatModerationRequestInputs3Type = "arrayOfChatModerationRequestInputs1"
	ChatModerationRequestInputs3TypeArrayOfArrayOfChatModerationRequestInputs2 ChatModerationRequestInputs3Type = "arrayOfArrayOfChatModerationRequestInputs2"
)

// ChatModerationRequestInputs3 - Chat to classify
type ChatModerationRequestInputs3 struct {
	ArrayOfChatModerationRequestInputs1        []ChatModerationRequestInputs1   `queryParam:"inline"`
	ArrayOfArrayOfChatModerationRequestInputs2 [][]ChatModerationRequestInputs2 `queryParam:"inline"`

	Type ChatModerationRequestInputs3Type
}

func CreateChatModerationRequestInputs3ArrayOfChatModerationRequestInputs1(arrayOfChatModerationRequestInputs1 []ChatModerationRequestInputs1) ChatModerationRequestInputs3 {
	typ := ChatModerationRequestInputs3TypeArrayOfChatModerationRequestInputs1

	return ChatModerationRequestInputs3{
		ArrayOfChatModerationRequestInputs1: arrayOfChatModerationRequestInputs1,
		Type:                                typ,
	}
}

func CreateChatModerationRequestInputs3ArrayOfArrayOfChatModerationRequestInputs2(arrayOfArrayOfChatModerationRequestInputs2 [][]ChatModerationRequestInputs2) ChatModerationRequestInputs3 {
	typ := ChatModerationRequestInputs3TypeArrayOfArrayOfChatModerationRequestInputs2

	return ChatModerationRequestInputs3{
		ArrayOfArrayOfChatModerationRequestInputs2: arrayOfArrayOfChatModerationRequestInputs2,
		Type: typ,
	}
}

func (u *ChatModerationRequestInputs3) UnmarshalJSON(data []byte) error {

	var arrayOfChatModerationRequestInputs1 []ChatModerationRequestInputs1 = []ChatModerationRequestInputs1{}
	if err := utils.UnmarshalJSON(data, &arrayOfChatModerationRequestInputs1, "", true, nil); err == nil {
		u.ArrayOfChatModerationRequestInputs1 = arrayOfChatModerationRequestInputs1
		u.Type = ChatModerationRequestInputs3TypeArrayOfChatModerationRequestInputs1
		return nil
	}

	var arrayOfArrayOfChatModerationRequestInputs2 [][]ChatModerationRequestInputs2 = [][]ChatModerationRequestInputs2{}
	if err := utils.UnmarshalJSON(data, &arrayOfArrayOfChatModerationRequestInputs2, "", true, nil); err == nil {
		u.ArrayOfArrayOfChatModerationRequestInputs2 = arrayOfArrayOfChatModerationRequestInputs2
		u.Type = ChatModerationRequestInputs3TypeArrayOfArrayOfChatModerationRequestInputs2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatModerationRequestInputs3", string(data))
}

func (u ChatModerationRequestInputs3) MarshalJSON() ([]byte, error) {
	if u.ArrayOfChatModerationRequestInputs1 != nil {
		return utils.MarshalJSON(u.ArrayOfChatModerationRequestInputs1, "", true)
	}

	if u.ArrayOfArrayOfChatModerationRequestInputs2 != nil {
		return utils.MarshalJSON(u.ArrayOfArrayOfChatModerationRequestInputs2, "", true)
	}

	return nil, errors.New("could not marshal union type ChatModerationRequestInputs3: all fields are null")
}

type ChatModerationRequest struct {
	// Chat to classify
	Inputs ChatModerationRequestInputs3 `json:"input"`
	Model  string                       `json:"model"`
}

func (o *ChatModerationRequest) GetInputs() ChatModerationRequestInputs3 {
	if o == nil {
		return ChatModerationRequestInputs3{}
	}
	return o.Inputs
}

func (o *ChatModerationRequest) GetModel() string {
	if o == nil {
		return ""
	}
	return o.Model
}
