// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type ClassifierTrainingParameters struct {
	TrainingSteps  *int64   `json:"training_steps,omitempty"`
	LearningRate   *float64 `default:"0.0001" json:"learning_rate"`
	WeightDecay    *float64 `json:"weight_decay,omitempty"`
	WarmupFraction *float64 `json:"warmup_fraction,omitempty"`
	Epochs         *float64 `json:"epochs,omitempty"`
	SeqLen         *int64   `json:"seq_len,omitempty"`
}

func (c ClassifierTrainingParameters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClassifierTrainingParameters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ClassifierTrainingParameters) GetTrainingSteps() *int64 {
	if o == nil {
		return nil
	}
	return o.TrainingSteps
}

func (o *ClassifierTrainingParameters) GetLearningRate() *float64 {
	if o == nil {
		return nil
	}
	return o.LearningRate
}

func (o *ClassifierTrainingParameters) GetWeightDecay() *float64 {
	if o == nil {
		return nil
	}
	return o.WeightDecay
}

func (o *ClassifierTrainingParameters) GetWarmupFraction() *float64 {
	if o == nil {
		return nil
	}
	return o.WarmupFraction
}

func (o *ClassifierTrainingParameters) GetEpochs() *float64 {
	if o == nil {
		return nil
	}
	return o.Epochs
}

func (o *ClassifierTrainingParameters) GetSeqLen() *int64 {
	if o == nil {
		return nil
	}
	return o.SeqLen
}
