// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
)

// CompletionFineTuningJobStatus - The current status of the fine-tuning job.
type CompletionFineTuningJobStatus string

const (
	CompletionFineTuningJobStatusQueued                CompletionFineTuningJobStatus = "QUEUED"
	CompletionFineTuningJobStatusStarted               CompletionFineTuningJobStatus = "STARTED"
	CompletionFineTuningJobStatusValidating            CompletionFineTuningJobStatus = "VALIDATING"
	CompletionFineTuningJobStatusValidated             CompletionFineTuningJobStatus = "VALIDATED"
	CompletionFineTuningJobStatusRunning               CompletionFineTuningJobStatus = "RUNNING"
	CompletionFineTuningJobStatusFailedValidation      CompletionFineTuningJobStatus = "FAILED_VALIDATION"
	CompletionFineTuningJobStatusFailed                CompletionFineTuningJobStatus = "FAILED"
	CompletionFineTuningJobStatusSuccess               CompletionFineTuningJobStatus = "SUCCESS"
	CompletionFineTuningJobStatusCancelled             CompletionFineTuningJobStatus = "CANCELLED"
	CompletionFineTuningJobStatusCancellationRequested CompletionFineTuningJobStatus = "CANCELLATION_REQUESTED"
)

func (e CompletionFineTuningJobStatus) ToPointer() *CompletionFineTuningJobStatus {
	return &e
}
func (e *CompletionFineTuningJobStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "QUEUED":
		fallthrough
	case "STARTED":
		fallthrough
	case "VALIDATING":
		fallthrough
	case "VALIDATED":
		fallthrough
	case "RUNNING":
		fallthrough
	case "FAILED_VALIDATION":
		fallthrough
	case "FAILED":
		fallthrough
	case "SUCCESS":
		fallthrough
	case "CANCELLED":
		fallthrough
	case "CANCELLATION_REQUESTED":
		*e = CompletionFineTuningJobStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CompletionFineTuningJobStatus: %v", v)
	}
}

type CompletionFineTuningJobIntegrationType string

const (
	CompletionFineTuningJobIntegrationTypeWandb CompletionFineTuningJobIntegrationType = "wandb"
)

type CompletionFineTuningJobIntegration struct {
	WandbIntegrationResult *WandbIntegrationResult `queryParam:"inline"`

	Type CompletionFineTuningJobIntegrationType
}

func CreateCompletionFineTuningJobIntegrationWandb(wandb WandbIntegrationResult) CompletionFineTuningJobIntegration {
	typ := CompletionFineTuningJobIntegrationTypeWandb

	return CompletionFineTuningJobIntegration{
		WandbIntegrationResult: &wandb,
		Type:                   typ,
	}
}

func (u *CompletionFineTuningJobIntegration) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "wandb":
		wandbIntegrationResult := new(WandbIntegrationResult)
		if err := utils.UnmarshalJSON(data, &wandbIntegrationResult, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == wandb) type WandbIntegrationResult within CompletionFineTuningJobIntegration: %w", string(data), err)
		}

		u.WandbIntegrationResult = wandbIntegrationResult
		u.Type = CompletionFineTuningJobIntegrationTypeWandb
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CompletionFineTuningJobIntegration", string(data))
}

func (u CompletionFineTuningJobIntegration) MarshalJSON() ([]byte, error) {
	if u.WandbIntegrationResult != nil {
		return utils.MarshalJSON(u.WandbIntegrationResult, "", true)
	}

	return nil, errors.New("could not marshal union type CompletionFineTuningJobIntegration: all fields are null")
}

type CompletionFineTuningJobRepositoryType string

const (
	CompletionFineTuningJobRepositoryTypeGithub CompletionFineTuningJobRepositoryType = "github"
)

type CompletionFineTuningJobRepository struct {
	GithubRepository *GithubRepository `queryParam:"inline"`

	Type CompletionFineTuningJobRepositoryType
}

func CreateCompletionFineTuningJobRepositoryGithub(github GithubRepository) CompletionFineTuningJobRepository {
	typ := CompletionFineTuningJobRepositoryTypeGithub

	return CompletionFineTuningJobRepository{
		GithubRepository: &github,
		Type:             typ,
	}
}

func (u *CompletionFineTuningJobRepository) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "github":
		githubRepository := new(GithubRepository)
		if err := utils.UnmarshalJSON(data, &githubRepository, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == github) type GithubRepository within CompletionFineTuningJobRepository: %w", string(data), err)
		}

		u.GithubRepository = githubRepository
		u.Type = CompletionFineTuningJobRepositoryTypeGithub
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CompletionFineTuningJobRepository", string(data))
}

func (u CompletionFineTuningJobRepository) MarshalJSON() ([]byte, error) {
	if u.GithubRepository != nil {
		return utils.MarshalJSON(u.GithubRepository, "", true)
	}

	return nil, errors.New("could not marshal union type CompletionFineTuningJobRepository: all fields are null")
}

type CompletionFineTuningJob struct {
	// The ID of the job.
	ID        string `json:"id"`
	AutoStart bool   `json:"auto_start"`
	Model     string `json:"model"`
	// The current status of the fine-tuning job.
	Status CompletionFineTuningJobStatus `json:"status"`
	// The UNIX timestamp (in seconds) for when the fine-tuning job was created.
	CreatedAt int64 `json:"created_at"`
	// The UNIX timestamp (in seconds) for when the fine-tuning job was last modified.
	ModifiedAt int64 `json:"modified_at"`
	// A list containing the IDs of uploaded files that contain training data.
	TrainingFiles []string `json:"training_files"`
	// A list containing the IDs of uploaded files that contain validation data.
	ValidationFiles []string `json:"validation_files,omitempty"`
	// The object type of the fine-tuning job.
	object *string `const:"job" json:"object"`
	// The name of the fine-tuned model that is being created. The value will be `null` if the fine-tuning job is still running.
	FineTunedModel *string `json:"fine_tuned_model,omitempty"`
	// Optional text/code that adds more context for the model. When given a `prompt` and a `suffix` the model will fill what is between them. When `suffix` is not provided, the model will simply execute completion starting with `prompt`.
	Suffix *string `json:"suffix,omitempty"`
	// A list of integrations enabled for your fine-tuning job.
	Integrations []CompletionFineTuningJobIntegration `json:"integrations,omitempty"`
	// Total number of tokens trained.
	TrainedTokens *int64       `json:"trained_tokens,omitempty"`
	Metadata      *JobMetadata `json:"metadata,omitempty"`
	// The type of job (`FT` for fine-tuning).
	jobType         *string                             `const:"completion" json:"job_type"`
	Hyperparameters CompletionTrainingParameters        `json:"hyperparameters"`
	Repositories    []CompletionFineTuningJobRepository `json:"repositories,omitempty"`
}

func (c CompletionFineTuningJob) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CompletionFineTuningJob) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"id", "auto_start", "model", "status", "created_at", "modified_at", "training_files", "hyperparameters"}); err != nil {
		return err
	}
	return nil
}

func (o *CompletionFineTuningJob) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CompletionFineTuningJob) GetAutoStart() bool {
	if o == nil {
		return false
	}
	return o.AutoStart
}

func (o *CompletionFineTuningJob) GetModel() string {
	if o == nil {
		return ""
	}
	return o.Model
}

func (o *CompletionFineTuningJob) GetStatus() CompletionFineTuningJobStatus {
	if o == nil {
		return CompletionFineTuningJobStatus("")
	}
	return o.Status
}

func (o *CompletionFineTuningJob) GetCreatedAt() int64 {
	if o == nil {
		return 0
	}
	return o.CreatedAt
}

func (o *CompletionFineTuningJob) GetModifiedAt() int64 {
	if o == nil {
		return 0
	}
	return o.ModifiedAt
}

func (o *CompletionFineTuningJob) GetTrainingFiles() []string {
	if o == nil {
		return []string{}
	}
	return o.TrainingFiles
}

func (o *CompletionFineTuningJob) GetValidationFiles() []string {
	if o == nil {
		return nil
	}
	return o.ValidationFiles
}

func (o *CompletionFineTuningJob) GetObject() *string {
	return types.String("job")
}

func (o *CompletionFineTuningJob) GetFineTunedModel() *string {
	if o == nil {
		return nil
	}
	return o.FineTunedModel
}

func (o *CompletionFineTuningJob) GetSuffix() *string {
	if o == nil {
		return nil
	}
	return o.Suffix
}

func (o *CompletionFineTuningJob) GetIntegrations() []CompletionFineTuningJobIntegration {
	if o == nil {
		return nil
	}
	return o.Integrations
}

func (o *CompletionFineTuningJob) GetTrainedTokens() *int64 {
	if o == nil {
		return nil
	}
	return o.TrainedTokens
}

func (o *CompletionFineTuningJob) GetMetadata() *JobMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *CompletionFineTuningJob) GetJobType() *string {
	return types.String("completion")
}

func (o *CompletionFineTuningJob) GetHyperparameters() CompletionTrainingParameters {
	if o == nil {
		return CompletionTrainingParameters{}
	}
	return o.Hyperparameters
}

func (o *CompletionFineTuningJob) GetRepositories() []CompletionFineTuningJobRepository {
	if o == nil {
		return nil
	}
	return o.Repositories
}
