// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
)

type ConversationAppendRequestHandoffExecution string

const (
	ConversationAppendRequestHandoffExecutionClient ConversationAppendRequestHandoffExecution = "client"
	ConversationAppendRequestHandoffExecutionServer ConversationAppendRequestHandoffExecution = "server"
)

func (e ConversationAppendRequestHandoffExecution) ToPointer() *ConversationAppendRequestHandoffExecution {
	return &e
}
func (e *ConversationAppendRequestHandoffExecution) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "client":
		fallthrough
	case "server":
		*e = ConversationAppendRequestHandoffExecution(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConversationAppendRequestHandoffExecution: %v", v)
	}
}

type ConversationAppendRequest struct {
	Inputs *ConversationInputs `json:"inputs,omitempty"`
	Stream *bool               `default:"false" json:"stream"`
	// Whether to store the results into our servers or not.
	Store            *bool                                      `default:"true" json:"store"`
	HandoffExecution *ConversationAppendRequestHandoffExecution `default:"server" json:"handoff_execution"`
	// White-listed arguments from the completion API
	CompletionArgs    *CompletionArgs        `json:"completion_args,omitempty"`
	ToolConfirmations []ToolCallConfirmation `json:"tool_confirmations,omitempty"`
}

func (c ConversationAppendRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConversationAppendRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ConversationAppendRequest) GetInputs() *ConversationInputs {
	if o == nil {
		return nil
	}
	return o.Inputs
}

func (o *ConversationAppendRequest) GetStream() *bool {
	if o == nil {
		return nil
	}
	return o.Stream
}

func (o *ConversationAppendRequest) GetStore() *bool {
	if o == nil {
		return nil
	}
	return o.Store
}

func (o *ConversationAppendRequest) GetHandoffExecution() *ConversationAppendRequestHandoffExecution {
	if o == nil {
		return nil
	}
	return o.HandoffExecution
}

func (o *ConversationAppendRequest) GetCompletionArgs() *CompletionArgs {
	if o == nil {
		return nil
	}
	return o.CompletionArgs
}

func (o *ConversationAppendRequest) GetToolConfirmations() []ToolCallConfirmation {
	if o == nil {
		return nil
	}
	return o.ToolConfirmations
}
