// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateFileResponse struct {
	// The unique identifier of the file.
	ID string `json:"id"`
	// The object type, which is always "file".
	Object string `json:"object"`
	// The size of the file, in bytes.
	SizeBytes int64 `json:"bytes"`
	// The UNIX timestamp (in seconds) of the event.
	CreatedAt int64 `json:"created_at"`
	// The name of the uploaded file.
	Filename   string      `json:"filename"`
	Purpose    FilePurpose `json:"purpose"`
	SampleType SampleType  `json:"sample_type"`
	NumLines   *int64      `json:"num_lines,omitempty"`
	Mimetype   *string     `json:"mimetype,omitempty"`
	Source     Source      `json:"source"`
	Signature  *string     `json:"signature,omitempty"`
}

func (o *CreateFileResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateFileResponse) GetObject() string {
	if o == nil {
		return ""
	}
	return o.Object
}

func (o *CreateFileResponse) GetSizeBytes() int64 {
	if o == nil {
		return 0
	}
	return o.SizeBytes
}

func (o *CreateFileResponse) GetCreatedAt() int64 {
	if o == nil {
		return 0
	}
	return o.CreatedAt
}

func (o *CreateFileResponse) GetFilename() string {
	if o == nil {
		return ""
	}
	return o.Filename
}

func (o *CreateFileResponse) GetPurpose() FilePurpose {
	if o == nil {
		return FilePurpose("")
	}
	return o.Purpose
}

func (o *CreateFileResponse) GetSampleType() SampleType {
	if o == nil {
		return SampleType("")
	}
	return o.SampleType
}

func (o *CreateFileResponse) GetNumLines() *int64 {
	if o == nil {
		return nil
	}
	return o.NumLines
}

func (o *CreateFileResponse) GetMimetype() *string {
	if o == nil {
		return nil
	}
	return o.Mimetype
}

func (o *CreateFileResponse) GetSource() Source {
	if o == nil {
		return Source("")
	}
	return o.Source
}

func (o *CreateFileResponse) GetSignature() *string {
	if o == nil {
		return nil
	}
	return o.Signature
}
