// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DocumentTextContent struct {
	Text string `json:"text"`
}

func (o *DocumentTextContent) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}
