// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"mockserver/internal/sdk/utils"
)

type FunctionCallEntryArgumentsType string

const (
	FunctionCallEntryArgumentsTypeMapOfAny FunctionCallEntryArgumentsType = "mapOfAny"
	FunctionCallEntryArgumentsTypeStr      FunctionCallEntryArgumentsType = "str"
)

type FunctionCallEntryArguments struct {
	MapOfAny map[string]any `queryParam:"inline"`
	Str      *string        `queryParam:"inline"`

	Type FunctionCallEntryArgumentsType
}

func CreateFunctionCallEntryArgumentsMapOfAny(mapOfAny map[string]any) FunctionCallEntryArguments {
	typ := FunctionCallEntryArgumentsTypeMapOfAny

	return FunctionCallEntryArguments{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func CreateFunctionCallEntryArgumentsStr(str string) FunctionCallEntryArguments {
	typ := FunctionCallEntryArgumentsTypeStr

	return FunctionCallEntryArguments{
		Str:  &str,
		Type: typ,
	}
}

func (u *FunctionCallEntryArguments) UnmarshalJSON(data []byte) error {

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		u.MapOfAny = mapOfAny
		u.Type = FunctionCallEntryArgumentsTypeMapOfAny
		return nil
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = FunctionCallEntryArgumentsTypeStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for FunctionCallEntryArguments", string(data))
}

func (u FunctionCallEntryArguments) MarshalJSON() ([]byte, error) {
	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type FunctionCallEntryArguments: all fields are null")
}
