// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetSignedURLResponse struct {
	URL string `json:"url"`
}

func (o *GetSignedURLResponse) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}
