// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
)

type ImageGenerationToolType string

const (
	ImageGenerationToolTypeImageGeneration ImageGenerationToolType = "image_generation"
)

func (e ImageGenerationToolType) ToPointer() *ImageGenerationToolType {
	return &e
}
func (e *ImageGenerationToolType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "image_generation":
		*e = ImageGenerationToolType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ImageGenerationToolType: %v", v)
	}
}

type ImageGenerationTool struct {
	ToolConfiguration *ToolConfiguration       `json:"tool_configuration,omitempty"`
	Type              *ImageGenerationToolType `default:"image_generation" json:"type"`
}

func (i ImageGenerationTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageGenerationTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ImageGenerationTool) GetToolConfiguration() *ToolConfiguration {
	if o == nil {
		return nil
	}
	return o.ToolConfiguration
}

func (o *ImageGenerationTool) GetType() *ImageGenerationToolType {
	if o == nil {
		return nil
	}
	return o.Type
}
