// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
)

type RealtimeTranscriptionError struct {
	type_ *string                          `const:"error" json:"type"`
	Error RealtimeTranscriptionErrorDetail `json:"error"`
}

func (r RealtimeTranscriptionError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RealtimeTranscriptionError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"error"}); err != nil {
		return err
	}
	return nil
}

func (o *RealtimeTranscriptionError) GetType() *string {
	return types.String("error")
}

func (o *RealtimeTranscriptionError) GetError() RealtimeTranscriptionErrorDetail {
	if o == nil {
		return RealtimeTranscriptionErrorDetail{}
	}
	return o.Error
}
