// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
)

type ThinkChunkThinkingType string

const (
	ThinkChunkThinkingTypeReferenceChunk ThinkChunkThinkingType = "ReferenceChunk"
	ThinkChunkThinkingTypeTextChunk      ThinkChunkThinkingType = "TextChunk"
)

type ThinkChunkThinking struct {
	ReferenceChunk *ReferenceChunk `queryParam:"inline"`
	TextChunk      *TextChunk      `queryParam:"inline"`

	Type ThinkChunkThinkingType
}

func CreateThinkChunkThinkingReferenceChunk(referenceChunk ReferenceChunk) ThinkChunkThinking {
	typ := ThinkChunkThinkingTypeReferenceChunk

	return ThinkChunkThinking{
		ReferenceChunk: &referenceChunk,
		Type:           typ,
	}
}

func CreateThinkChunkThinkingTextChunk(textChunk TextChunk) ThinkChunkThinking {
	typ := ThinkChunkThinkingTypeTextChunk

	return ThinkChunkThinking{
		TextChunk: &textChunk,
		Type:      typ,
	}
}

func (u *ThinkChunkThinking) UnmarshalJSON(data []byte) error {

	var referenceChunk ReferenceChunk = ReferenceChunk{}
	if err := utils.UnmarshalJSON(data, &referenceChunk, "", true, nil); err == nil {
		u.ReferenceChunk = &referenceChunk
		u.Type = ThinkChunkThinkingTypeReferenceChunk
		return nil
	}

	var textChunk TextChunk = TextChunk{}
	if err := utils.UnmarshalJSON(data, &textChunk, "", true, nil); err == nil {
		u.TextChunk = &textChunk
		u.Type = ThinkChunkThinkingTypeTextChunk
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ThinkChunkThinking", string(data))
}

func (u ThinkChunkThinking) MarshalJSON() ([]byte, error) {
	if u.ReferenceChunk != nil {
		return utils.MarshalJSON(u.ReferenceChunk, "", true)
	}

	if u.TextChunk != nil {
		return utils.MarshalJSON(u.TextChunk, "", true)
	}

	return nil, errors.New("could not marshal union type ThinkChunkThinking: all fields are null")
}

type ThinkChunk struct {
	type_    *string              `const:"thinking" json:"type"`
	Thinking []ThinkChunkThinking `json:"thinking"`
	// Whether the thinking chunk is closed or not. Currently only used for prefixing.
	Closed *bool `json:"closed,omitempty"`
}

func (t ThinkChunk) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ThinkChunk) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"thinking"}); err != nil {
		return err
	}
	return nil
}

func (o *ThinkChunk) GetType() *string {
	return types.String("thinking")
}

func (o *ThinkChunk) GetThinking() []ThinkChunkThinking {
	if o == nil {
		return []ThinkChunkThinking{}
	}
	return o.Thinking
}

func (o *ThinkChunk) GetClosed() *bool {
	if o == nil {
		return nil
	}
	return o.Closed
}
