// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type ToolConfiguration struct {
	Exclude              []string `json:"exclude,omitempty"`
	Include              []string `json:"include,omitempty"`
	RequiresConfirmation []string `json:"requires_confirmation,omitempty"`
}

func (t ToolConfiguration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToolConfiguration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ToolConfiguration) GetExclude() []string {
	if o == nil {
		return nil
	}
	return o.Exclude
}

func (o *ToolConfiguration) GetInclude() []string {
	if o == nil {
		return nil
	}
	return o.Include
}

func (o *ToolConfiguration) GetRequiresConfirmation() []string {
	if o == nil {
		return nil
	}
	return o.RequiresConfirmation
}
