// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"time"
)

type ToolExecutionDoneEventNameType string

const (
	ToolExecutionDoneEventNameTypeBuiltInConnectors ToolExecutionDoneEventNameType = "BuiltInConnectors"
	ToolExecutionDoneEventNameTypeStr               ToolExecutionDoneEventNameType = "str"
)

type ToolExecutionDoneEventName struct {
	BuiltInConnectors *BuiltInConnectors `queryParam:"inline"`
	Str               *string            `queryParam:"inline"`

	Type ToolExecutionDoneEventNameType
}

func CreateToolExecutionDoneEventNameBuiltInConnectors(builtInConnectors BuiltInConnectors) ToolExecutionDoneEventName {
	typ := ToolExecutionDoneEventNameTypeBuiltInConnectors

	return ToolExecutionDoneEventName{
		BuiltInConnectors: &builtInConnectors,
		Type:              typ,
	}
}

func CreateToolExecutionDoneEventNameStr(str string) ToolExecutionDoneEventName {
	typ := ToolExecutionDoneEventNameTypeStr

	return ToolExecutionDoneEventName{
		Str:  &str,
		Type: typ,
	}
}

func (u *ToolExecutionDoneEventName) UnmarshalJSON(data []byte) error {

	var builtInConnectors BuiltInConnectors = BuiltInConnectors("")
	if err := utils.UnmarshalJSON(data, &builtInConnectors, "", true, nil); err == nil {
		u.BuiltInConnectors = &builtInConnectors
		u.Type = ToolExecutionDoneEventNameTypeBuiltInConnectors
		return nil
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = ToolExecutionDoneEventNameTypeStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ToolExecutionDoneEventName", string(data))
}

func (u ToolExecutionDoneEventName) MarshalJSON() ([]byte, error) {
	if u.BuiltInConnectors != nil {
		return utils.MarshalJSON(u.BuiltInConnectors, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type ToolExecutionDoneEventName: all fields are null")
}

type ToolExecutionDoneEvent struct {
	type_       *string                    `const:"tool.execution.done" json:"type"`
	CreatedAt   *time.Time                 `json:"created_at,omitempty"`
	OutputIndex *int64                     `default:"0" json:"output_index"`
	ID          string                     `json:"id"`
	Name        ToolExecutionDoneEventName `json:"name"`
	Info        map[string]any             `json:"info,omitempty"`
}

func (t ToolExecutionDoneEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToolExecutionDoneEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"id", "name"}); err != nil {
		return err
	}
	return nil
}

func (o *ToolExecutionDoneEvent) GetType() *string {
	return types.String("tool.execution.done")
}

func (o *ToolExecutionDoneEvent) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *ToolExecutionDoneEvent) GetOutputIndex() *int64 {
	if o == nil {
		return nil
	}
	return o.OutputIndex
}

func (o *ToolExecutionDoneEvent) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ToolExecutionDoneEvent) GetName() ToolExecutionDoneEventName {
	if o == nil {
		return ToolExecutionDoneEventName{}
	}
	return o.Name
}

func (o *ToolExecutionDoneEvent) GetInfo() map[string]any {
	if o == nil {
		return nil
	}
	return o.Info
}
