// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
)

type UnarchiveModelResponse struct {
	ID       string  `json:"id"`
	object   *string `const:"model" json:"object"`
	Archived *bool   `default:"false" json:"archived"`
}

func (u UnarchiveModelResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnarchiveModelResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (o *UnarchiveModelResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UnarchiveModelResponse) GetObject() *string {
	return types.String("model")
}

func (o *UnarchiveModelResponse) GetArchived() *bool {
	if o == nil {
		return nil
	}
	return o.Archived
}
