// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateLibraryRequest struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

func (o *UpdateLibraryRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateLibraryRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}
