// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
)

type WandbIntegrationResult struct {
	type_ *string `const:"wandb" json:"type"`
	// The name of the project that the new run will be created under.
	Project string `json:"project"`
	// A display name to set for the run. If not set, will use the job ID as the name.
	Name    *string `json:"name,omitempty"`
	RunName *string `json:"run_name,omitempty"`
	URL     *string `json:"url,omitempty"`
}

func (w WandbIntegrationResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WandbIntegrationResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, []string{"project"}); err != nil {
		return err
	}
	return nil
}

func (o *WandbIntegrationResult) GetType() *string {
	return types.String("wandb")
}

func (o *WandbIntegrationResult) GetProject() string {
	if o == nil {
		return ""
	}
	return o.Project
}

func (o *WandbIntegrationResult) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *WandbIntegrationResult) GetRunName() *string {
	if o == nil {
		return nil
	}
	return o.RunName
}

func (o *WandbIntegrationResult) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}
