// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type AgentsAPIV1ConversationsHistoryRequest struct {
	// ID of the conversation from which we are fetching entries.
	ConversationID string `pathParam:"style=simple,explode=false,name=conversation_id"`
}

func (o *AgentsAPIV1ConversationsHistoryRequest) GetConversationID() string {
	if o == nil {
		return ""
	}
	return o.ConversationID
}

type AgentsAPIV1ConversationsHistoryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ConversationHistory *components.ConversationHistory
}

func (o *AgentsAPIV1ConversationsHistoryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AgentsAPIV1ConversationsHistoryResponse) GetConversationHistory() *components.ConversationHistory {
	if o == nil {
		return nil
	}
	return o.ConversationHistory
}
