// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type AgentsAPIV1AgentsListVersionAliasesRequest struct {
	AgentID string `pathParam:"style=simple,explode=false,name=agent_id"`
}

func (o *AgentsAPIV1AgentsListVersionAliasesRequest) GetAgentID() string {
	if o == nil {
		return ""
	}
	return o.AgentID
}

type AgentsAPIV1AgentsListVersionAliasesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseV1AgentsListVersionAliases []components.AgentAliasResponse
}

func (o *AgentsAPIV1AgentsListVersionAliasesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AgentsAPIV1AgentsListVersionAliasesResponse) GetResponseV1AgentsListVersionAliases() []components.AgentAliasResponse {
	if o == nil {
		return nil
	}
	return o.ResponseV1AgentsListVersionAliases
}
