// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type JobsAPIRoutesBatchCancelBatchJobRequest struct {
	JobID string `pathParam:"style=simple,explode=false,name=job_id"`
}

func (o *JobsAPIRoutesBatchCancelBatchJobRequest) GetJobID() string {
	if o == nil {
		return ""
	}
	return o.JobID
}

type JobsAPIRoutesBatchCancelBatchJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	BatchJob *components.BatchJob
}

func (o *JobsAPIRoutesBatchCancelBatchJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *JobsAPIRoutesBatchCancelBatchJobResponse) GetBatchJob() *components.BatchJob {
	if o == nil {
		return nil
	}
	return o.BatchJob
}
