// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types/stream"
)

type StreamFimResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A stream of FIM completion events
	CompletionEvent *stream.EventStream[components.CompletionEvent]
}

func (o *StreamFimResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *StreamFimResponse) GetCompletionEvent() *stream.EventStream[components.CompletionEvent] {
	if o == nil {
		return nil
	}
	return o.CompletionEvent
}
