workflowVersion: 1.0.0
speakeasyVersion:  1.568.2
sources:
    mistral-azure-source:
        inputs:
            - location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-azure:sha256:c5931a7e0cc2db844149d71db57dfc2178665f0400bc26c90ee113795ea2872f
    mistral-google-cloud-source:
        inputs:
            - location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-google-cloud:sha256:4a5343e63c6a78152e472b00ccc46d7bcb15594496bc94c8040039d3a9d4c5f8
    mistral-openapi:
        inputs:
            - location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi:sha256:21244d618cafcc163c3aa4acbc443ca16c63b8614632b65b87fbb2c4066987f3
targets:
    mistralai-azure-sdk:
        target: python
        source: mistral-azure-source
        output: ./packages/mistralai_azure
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-azure-code-samples
            blocking: false
    mistralai-gcp-sdk:
        target: python
        source: mistral-google-cloud-source
        output: ./packages/mistralai_gcp
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-google-cloud-code-samples
            blocking: false
    mistralai-sdk:
        target: python
        source: mistral-openapi
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-code-samples
            blocking: false
