workflowVersion: 1.0.0
# speakeasyVersion is pinned to unblock https://github.com/mistralai/client-python/pull/173
# The speakeasy run was appending `_` to some attributes to avoid conflicts with reserved keywords.
# This would have change the SDK APIs and break the existing clients which we don't want.
speakeasyVersion: 1.462.2
sources:
    mistral-azure-source:
        inputs:
            - location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-azure:main
    mistral-google-cloud-source:
        inputs:
            - location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-google-cloud:main
    mistral-openapi:
        inputs:
            - location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi:main
targets:
    mistralai-azure-sdk:
        target: python
        source: mistral-azure-source
        output: ./packages/mistralai_azure
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-azure-code-samples
            blocking: false
    mistralai-gcp-sdk:
        target: python
        source: mistral-google-cloud-source
        output: ./packages/mistralai_gcp
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-google-cloud-code-samples
            blocking: false
    mistralai-sdk:
        target: python
        source: mistral-openapi
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-code-samples
            blocking: false
