workflowVersion: 1.0.0
speakeasyVersion: 1.568.2
sources:
    mistral-azure-source:
        inputs:
            -   location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-azure:main
    mistral-google-cloud-source:
        inputs:
            -   location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-google-cloud:main
    mistral-openapi:
        inputs:
            -   location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi:main
targets:
    mistralai-azure-sdk:
        target: python
        source: mistral-azure-source
        output: ./packages/mistralai_azure
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-azure-code-samples
            blocking: false
    mistralai-gcp-sdk:
        target: python
        source: mistral-google-cloud-source
        output: ./packages/mistralai_gcp
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-google-cloud-code-samples
            blocking: false
    mistralai-sdk:
        target: python
        source: mistral-openapi
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-code-samples
            blocking: false
