"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


DocumentLibraryToolType = Literal["document_library",]


class DocumentLibraryToolTypedDict(TypedDict):
    library_ids: List[str]
    r"""Ids of the library in which to search."""
    type: NotRequired[DocumentLibraryToolType]


class DocumentLibraryTool(BaseModel):
    library_ids: List[str]
    r"""Ids of the library in which to search."""

    type: Optional[DocumentLibraryToolType] = "document_library"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
