"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .functioncallentryarguments import (
    FunctionCallEntryArguments,
    FunctionCallEntryArgumentsTypedDict,
)
from datetime import datetime
from mistralai.sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


FunctionCallEntryObject = Literal["entry",]


FunctionCallEntryType = Literal["function.call",]


class FunctionCallEntryTypedDict(TypedDict):
    tool_call_id: str
    name: str
    arguments: FunctionCallEntryArgumentsTypedDict
    object: NotRequired[FunctionCallEntryObject]
    type: NotRequired[FunctionCallEntryType]
    created_at: NotRequired[datetime]
    completed_at: NotRequired[Nullable[datetime]]
    id: NotRequired[str]


class FunctionCallEntry(BaseModel):
    tool_call_id: str

    name: str

    arguments: FunctionCallEntryArguments

    object: Optional[FunctionCallEntryObject] = "entry"

    type: Optional[FunctionCallEntryType] = "function.call"

    created_at: Optional[datetime] = None

    completed_at: OptionalNullable[datetime] = UNSET

    id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["object", "type", "created_at", "completed_at", "id"])
        nullable_fields = set(["completed_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
