// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
)

type UsageInfo struct {
	PromptTokens         *int64                                   `default:"0" json:"prompt_tokens"`
	CompletionTokens     *int64                                   `default:"0" json:"completion_tokens"`
	TotalTokens          *int64                                   `default:"0" json:"total_tokens"`
	PromptAudioSeconds   optionalnullable.OptionalNullable[int64] `json:"prompt_audio_seconds,omitempty"`
	AdditionalProperties map[string]any                           `additionalProperties:"true" json:"-"`
}

func (u UsageInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UsageInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *UsageInfo) GetPromptTokens() *int64 {
	if o == nil {
		return nil
	}
	return o.PromptTokens
}

func (o *UsageInfo) GetCompletionTokens() *int64 {
	if o == nil {
		return nil
	}
	return o.CompletionTokens
}

func (o *UsageInfo) GetTotalTokens() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalTokens
}

func (o *UsageInfo) GetPromptAudioSeconds() optionalnullable.OptionalNullable[int64] {
	if o == nil {
		return nil
	}
	return o.PromptAudioSeconds
}

func (o *UsageInfo) GetAdditionalProperties() map[string]any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
