"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: cc807b30de19

import importlib.metadata

__title__: str = "mistralai"
<<<<<<< Current (Your changes)
__version__: str = "2.5.0"
=======
__version__: str = "2.5.2"
>>>>>>> New (Generated by Speakeasy)
__openapi_doc_version__: str = "1.0.0"
__gen_version__: str = "2.884.13"
<<<<<<< Current (Your changes)
__user_agent__: str = "speakeasy-sdk/python 2.5.0 2.884.13 1.0.0 mistralai"
=======
__user_agent__: str = "speakeasy-sdk/python 2.5.2 2.884.13 1.0.0 mistralai"
>>>>>>> New (Generated by Speakeasy)

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
