"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 2c2b641de1b6

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from mistralai.client.ingestion_pipeline_configurations import (
    IngestionPipelineConfigurations,
)
from mistralai.client.search_indexes import SearchIndexes
from typing import Optional


class Rag(BaseSDK):
    ingestion_pipeline_configurations: IngestionPipelineConfigurations
    search_indexes: SearchIndexes

    def __init__(
        self, sdk_config: SDKConfiguration, parent_ref: Optional[object] = None
    ) -> None:
        BaseSDK.__init__(self, sdk_config, parent_ref=parent_ref)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.ingestion_pipeline_configurations = IngestionPipelineConfigurations(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.search_indexes = SearchIndexes(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
