// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ResponseFormats string

const (
	ResponseFormatsText       ResponseFormats = "text"
	ResponseFormatsJSONObject ResponseFormats = "json_object"
	ResponseFormatsJSONSchema ResponseFormats = "json_schema"
)

func (e ResponseFormats) ToPointer() *ResponseFormats {
	return &e
}
func (e *ResponseFormats) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		fallthrough
	case "json_object":
		fallthrough
	case "json_schema":
		*e = ResponseFormats(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ResponseFormats: %v", v)
	}
}
