name: SDK Contract Tests
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

"on":
  workflow_dispatch:
    inputs:
      target:
        description: "Target to test (default: all)"
        type: choice
        options:
          - all
          - mistralai-azure-sdk
          - mistralai-gcp-sdk
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "packages/**"
      - ".speakeasy/**"
      - "tests/**"

jobs:
  test:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-test.yaml@v15
    with:
      target: ${{ github.event.inputs.target || 'all' }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
