name: Lint / Test / Publish

on:
  push:
    branches: ["main"]

    # We only deploy on tags and main branch
    tags:
      # Only run on tags that match the following regex
      # This will match tags like 1.0.0, 1.0.1, etc.
      - "[0-9]+.[0-9]+.[0-9]+"

  # Lint and test on pull requests
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: pantsbuild/actions/init-pants@v8
      with:
        gha-cache-key: v0
        named-caches-hash: ${{ hashFiles('poetry.lock') }}
        cache-lmdb-store: 'true'
    - name: Check BUILD files
      run: |
        pants tailor --check update-build-files --check ::
    - name: Lint
      run: |
        pants lint ::
    - name: Typecheck
      run: |
        pants check src/mistralai src/mistralai/models
    - name: Test
      run: |
        pants test ::
    - name: Upload pants log
      uses: actions/upload-artifact@v3
      with:
        name: pants-log-${{ matrix.python-version }}
        path: .pants.d/workdir/pants.log
      if: always()

  publish:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set python version to 3.11
      - name: set python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install Build stuff
      - name: Install Dependencies
        run: |
          pip install poetry \
          && poetry config virtualenvs.create false \
          && poetry install

      # build package using poetry
      - name: Build Package
        run: |
          poetry build

      # Publish to PyPi
      - name: Pypi publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
